import type { Article } from "./types";
import { DLPT_ARTICLES } from "./dlpt";
import { DLPT_ARTICLES_2 } from "./dlpt2";

/**
 * Graded news stories. These are original, news-style texts written for
 * learners (modelled on typical Korean news topics and phrasing) so every
 * word is covered by the built-in dictionary. Real articles can be added via
 * "Paste your own" in the News tab.
 */
const BASE_ARTICLES: Article[] = [
  {
    id: "a1-first-snow",
    kind: "news",
    title: "서울에 첫눈이 왔어요",
    titleEn: "First snow in Seoul",
    topic: "Life",
    level: "A1",
    date: "2026-11-28",
    emoji: "❄️",
    sentences: [
      { ko: "오늘 아침 서울에 첫눈이 왔어요.", en: "The first snow fell in Seoul this morning." },
      { ko: "날씨가 아주 추워요.", en: "The weather is very cold." },
      { ko: "사람들은 두꺼운 옷을 입었어요.", en: "People wore thick clothes." },
      { ko: "아이들은 공원에서 눈사람을 만들었어요.", en: "Children made snowmen in the park." },
      { ko: "내일은 눈이 오지 않아요.", en: "It won't snow tomorrow." },
      { ko: "하지만 바람이 많이 불어요.", en: "But the wind will blow hard." },
      { ko: "따뜻한 옷을 입으세요!", en: "Wear warm clothes!" },
    ],
  },
  {
    id: "a1-new-cafe",
    kind: "news",
    title: "학교 앞에 새 카페가 열었어요",
    titleEn: "A new café opened by the school",
    topic: "Life",
    level: "A1",
    date: "2026-09-14",
    emoji: "☕",
    sentences: [
      { ko: "어제 학교 앞에 새 카페가 문을 열었어요.", en: "Yesterday a new café opened in front of the school." },
      { ko: "카페 이름은 봄이에요.", en: "The café is called Bom (Spring)." },
      { ko: "커피가 싸고 맛있어요.", en: "The coffee is cheap and tasty." },
      { ko: "아메리카노는 2,000원이에요.", en: "An americano is 2,000 won." },
      { ko: "학생들이 카페에서 공부해요.", en: "Students study at the café." },
      { ko: "주인은 학생들이 많이 와서 기뻐요.", en: "The owner is happy because many students come." },
      { ko: "카페는 아침 여덟 시에 문을 열어요.", en: "The café opens at eight in the morning." },
    ],
  },
  {
    id: "a2-subway-fare",
    kind: "news",
    title: "지하철 요금이 오릅니다",
    titleEn: "Subway fares are going up",
    topic: "Society",
    level: "A2",
    date: "2026-10-02",
    emoji: "🚇",
    sentences: [
      { ko: "다음 달부터 서울 지하철 요금이 오릅니다.", en: "Starting next month, Seoul subway fares will rise." },
      { ko: "기본 요금은 1,400원에서 1,550원이 됩니다.", en: "The base fare will go from 1,400 won to 1,550 won." },
      { ko: "서울시는 버스 요금도 함께 올릴 계획입니다.", en: "The city also plans to raise bus fares." },
      { ko: "시민들의 생각은 다릅니다.", en: "Citizens have different opinions." },
      { ko: "한 대학생은 매일 지하철을 타서 돈이 많이 든다고 말했습니다.", en: "One university student said it costs a lot because they ride the subway every day." },
      { ko: "그러나 서울시는 지하철 서비스가 더 좋아질 것이라고 설명했습니다.", en: "However, the city explained that subway service will get better." },
    ],
  },
  {
    id: "a2-ramyeon",
    kind: "news",
    title: "한국 라면, 세계에서 인기",
    titleEn: "Korean ramyeon is a global hit",
    topic: "Culture",
    level: "A2",
    date: "2026-08-21",
    emoji: "🍜",
    sentences: [
      { ko: "요즘 한국 라면이 세계에서 큰 인기를 얻고 있습니다.", en: "These days Korean ramyeon is becoming very popular around the world." },
      { ko: "작년 라면 수출이 처음으로 10억 달러를 넘었습니다.", en: "Last year ramyeon exports passed one billion dollars for the first time." },
      { ko: "특히 미국과 중국에서 많이 팔렸습니다.", en: "It sold especially well in the US and China." },
      { ko: "외국인들은 매운 맛을 좋아합니다.", en: "Foreigners like the spicy flavor." },
      { ko: "유튜브에서 매운 라면을 먹는 영상도 인기가 많습니다.", en: "Videos of people eating spicy ramyeon on YouTube are popular too." },
      { ko: "한 회사는 올해 새 공장을 지을 예정입니다.", en: "One company plans to build a new factory this year." },
    ],
  },
  {
    id: "a2-phone-time",
    kind: "news",
    title: "하루 스마트폰 사용 시간은?",
    titleEn: "How long do we use our phones?",
    topic: "Tech",
    level: "A2",
    date: "2026-07-09",
    emoji: "📱",
    sentences: [
      { ko: "한국 사람들은 하루에 스마트폰을 얼마나 쓸까요?", en: "How much do Koreans use their smartphones in a day?" },
      { ko: "새로운 조사에 따르면 평균 사용 시간은 다섯 시간입니다.", en: "According to a new survey, average use is five hours." },
      { ko: "십 대와 이십 대가 가장 많이 사용합니다.", en: "Teens and people in their twenties use them the most." },
      { ko: "사람들은 주로 메시지를 보내고 동영상을 봅니다.", en: "People mostly send messages and watch videos." },
      { ko: "전문가들은 자기 전에는 휴대폰을 보지 말라고 조언합니다.", en: "Experts advise not looking at your phone before bed." },
      { ko: "잠을 잘 자는 것이 건강에 중요하기 때문입니다.", en: "That's because sleeping well is important for your health." },
    ],
  },
  {
    id: "b1-ai-translator",
    kind: "news",
    title: "AI 번역 앱, 외국인 관광객에게 인기",
    titleEn: "AI translation apps are a hit with tourists",
    topic: "Tech",
    level: "B1",
    date: "2026-09-30",
    emoji: "🤖",
    sentences: [
      { ko: "한국을 찾는 외국인 관광객이 늘면서 AI 번역 앱 사용도 크게 증가했습니다.", en: "As more foreign tourists visit Korea, use of AI translation apps has risen sharply." },
      { ko: "관광객들은 식당에서 메뉴를 읽거나 길을 물을 때 번역 앱을 자주 이용합니다.", en: "Tourists often use translation apps to read menus at restaurants or ask for directions." },
      { ko: "최근에는 사진을 찍으면 바로 번역해 주는 기능이 특히 인기를 끌고 있습니다.", en: "Recently, a feature that translates instantly when you take a photo has been especially popular." },
      { ko: "한 프랑스 관광객은 한국어를 몰라도 여행하는 데 문제가 없었다고 말했습니다.", en: "One French tourist said they had no trouble traveling even without knowing Korean." },
      { ko: "하지만 번역이 항상 정확한 것은 아닙니다.", en: "But translations are not always accurate." },
      { ko: "전문가들은 간단한 한국어 인사말을 배우면 여행이 더 즐거워진다고 말합니다.", en: "Experts say learning simple Korean greetings makes a trip more enjoyable." },
    ],
  },
  {
    id: "b1-drama-tourism",
    kind: "news",
    title: "드라마 촬영지 찾는 관광객 증가",
    titleEn: "More tourists visit drama filming spots",
    topic: "Culture",
    level: "B1",
    date: "2026-06-17",
    emoji: "🎬",
    sentences: [
      { ko: "인기 드라마의 촬영지를 방문하는 관광객이 많아지고 있습니다.", en: "More and more tourists are visiting the filming locations of popular dramas." },
      { ko: "강원도의 한 작은 바닷가 마을은 드라마가 방송된 후 방문객이 세 배로 늘었습니다.", en: "In one small seaside village in Gangwon Province, visitors tripled after a drama aired." },
      { ko: "관광객들은 드라마 주인공처럼 사진을 찍고 지역 음식을 맛봅니다.", en: "Tourists take photos like the drama's main characters and taste local food." },
      { ko: "마을 주민들은 경제에 도움이 된다며 반기고 있습니다.", en: "Villagers welcome it, saying it helps the economy." },
      { ko: "그러나 일부 주민들은 쓰레기와 소음 때문에 불편을 겪고 있습니다.", en: "However, some residents are suffering inconvenience because of trash and noise." },
      { ko: "지역 정부는 관광객을 위한 안내 센터를 열고 쓰레기통을 더 설치하기로 했습니다.", en: "The local government decided to open an information center for tourists and install more trash cans." },
    ],
  },
  {
    id: "b1-single-households",
    kind: "news",
    title: "혼자 사는 사람이 늘어난다",
    titleEn: "More people are living alone",
    topic: "Society",
    level: "B1",
    date: "2026-05-04",
    emoji: "🏠",
    sentences: [
      { ko: "한국에서 혼자 사는 1인 가구가 계속 늘어나고 있습니다.", en: "Single-person households in Korea keep increasing." },
      { ko: "통계에 따르면 전체 가구의 삼분의 일이 1인 가구입니다.", en: "According to statistics, one third of all households are single-person households." },
      { ko: "이에 따라 작은 크기의 음식과 가전제품이 잘 팔리고 있습니다.", en: "Accordingly, small-sized food and home appliances are selling well." },
      { ko: "편의점 도시락 판매도 지난해보다 이십 퍼센트 증가했습니다.", en: "Convenience-store lunch box sales also rose 20 percent from last year." },
      { ko: "혼자 밥을 먹는 혼밥 문화도 이제 자연스러운 일이 되었습니다.", en: "Honbap culture — eating alone — has now become a natural thing too." },
      { ko: "전문가들은 이런 변화가 앞으로도 계속될 것으로 예상합니다.", en: "Experts expect this change to continue in the future." },
    ],
  },
  {
    id: "b2-ev-chargers",
    kind: "news",
    title: "전기차 충전소 확대 나선다",
    titleEn: "Government moves to expand EV chargers",
    topic: "Tech",
    level: "B2",
    date: "2026-10-01",
    emoji: "🔌",
    sentences: [
      { ko: "정부가 전기차 보급을 늘리기 위해 충전소를 대폭 확대하기로 했습니다.", en: "The government has decided to greatly expand charging stations to boost EV adoption." },
      { ko: "계획에 따르면 2030년까지 전국에 충전기 백만 대를 설치할 예정입니다.", en: "Under the plan, one million chargers will be installed nationwide by 2030." },
      { ko: "그동안 운전자들은 충전소가 부족해 장거리 운전을 꺼려 왔습니다.", en: "Until now, drivers have been reluctant to drive long distances because of a lack of charging stations." },
      { ko: "특히 아파트 주차장의 충전 시설 부족이 가장 큰 문제로 지적되었습니다.", en: "In particular, the shortage of charging facilities in apartment parking lots was pointed out as the biggest problem." },
      { ko: "정부는 충전 요금을 낮추는 방안도 함께 검토하고 있습니다.", en: "The government is also reviewing ways to lower charging fees." },
      { ko: "업계에서는 이번 정책이 전기차 시장 성장에 긍정적인 영향을 줄 것으로 기대하고 있습니다.", en: "The industry expects this policy to have a positive effect on the growth of the EV market." },
    ],
  },
  {
    id: "b2-kimchi-climate",
    kind: "news",
    title: "기후 변화로 배추값 상승, 김장 비상",
    titleEn: "Climate change drives up cabbage prices",
    topic: "World",
    level: "B2",
    date: "2026-10-04",
    emoji: "🥬",
    sentences: [
      { ko: "기후 변화로 여름 기온이 오르면서 배추 생산량이 크게 줄었습니다.", en: "As summer temperatures rose due to climate change, cabbage production fell sharply." },
      { ko: "배추는 서늘한 날씨에서 잘 자라는 채소이기 때문에 더위에 약합니다.", en: "Napa cabbage grows well in cool weather, so it is vulnerable to heat." },
      { ko: "이로 인해 배추 가격이 작년보다 두 배 가까이 올랐습니다.", en: "As a result, cabbage prices have nearly doubled from last year." },
      { ko: "김장을 준비하는 가정에서는 부담이 커졌다는 목소리가 나오고 있습니다.", en: "Households preparing for kimjang say the burden has grown." },
      { ko: "일부 농가는 더위에 강한 새 품종을 시험 재배하고 있습니다.", en: "Some farms are trial-growing new heat-resistant varieties." },
      { ko: "전문가들은 장기적으로 농업 전체가 기후 변화에 적응해야 한다고 강조합니다.", en: "Experts stress that in the long run, agriculture as a whole must adapt to climate change." },
    ],
  },
];

/** Newest first, so the exam-prep stories lead the feed. */
export const ARTICLES: Article[] = [...DLPT_ARTICLES, ...DLPT_ARTICLES_2, ...BASE_ARTICLES].sort((a, b) => b.date.localeCompare(a.date));
