import type { Clip } from "./types";

/**
 * Short-form clips: vertical, swipeable, sentence-synced audio scenes
 * (spoken with the device's Korean text-to-speech voice).
 */
export const CLIPS: Clip[] = [
  {
    id: "c-intro",
    kind: "clip",
    title: "자기소개",
    titleEn: "Introducing yourself",
    topic: "Life",
    level: "A1",
    emoji: "👋",
    gradient: "from-pink-500 to-orange-400",
    sentences: [
      { ko: "안녕하세요!", en: "Hello!" },
      { ko: "제 이름은 민수예요.", en: "My name is Minsu." },
      { ko: "저는 부산에서 왔어요.", en: "I'm from Busan." },
      { ko: "저는 대학생이에요.", en: "I'm a university student." },
      { ko: "취미는 요리예요.", en: "My hobby is cooking." },
      { ko: "만나서 반가워요!", en: "Nice to meet you!" },
    ],
  },
  {
    id: "c-convenience-store",
    kind: "clip",
    title: "편의점에서",
    titleEn: "At the convenience store",
    topic: "Life",
    level: "A1",
    emoji: "🏪",
    gradient: "from-emerald-500 to-teal-600",
    sentences: [
      { ko: "어서 오세요!", en: "Welcome!", speaker: "A" },
      { ko: "이거 얼마예요?", en: "How much is this?", speaker: "B" },
      { ko: "삼천 원이에요.", en: "It's 3,000 won.", speaker: "A" },
      { ko: "카드로 계산할게요.", en: "I'll pay by card.", speaker: "B" },
      { ko: "봉투 필요하세요?", en: "Do you need a bag?", speaker: "A" },
      { ko: "아니요, 괜찮아요.", en: "No, I'm fine.", speaker: "B" },
    ],
  },
  {
    id: "c-cafe-order",
    kind: "clip",
    title: "카페에서 주문하기",
    titleEn: "Ordering at a café",
    topic: "Life",
    level: "A1",
    emoji: "🧋",
    gradient: "from-amber-500 to-rose-500",
    sentences: [
      { ko: "주문하시겠어요?", en: "Are you ready to order?", speaker: "A" },
      { ko: "아이스 아메리카노 한 잔 주세요.", en: "One iced americano, please.", speaker: "B" },
      { ko: "드시고 가세요?", en: "For here?", speaker: "A" },
      { ko: "아니요, 가져갈게요.", en: "No, to go.", speaker: "B" },
      { ko: "잠시만 기다려 주세요.", en: "Please wait a moment.", speaker: "A" },
    ],
  },
  {
    id: "c-weather",
    kind: "clip",
    title: "오늘의 날씨",
    titleEn: "Today's weather",
    topic: "Life",
    level: "A1",
    emoji: "🌤️",
    gradient: "from-sky-500 to-indigo-500",
    sentences: [
      { ko: "안녕하세요, 오늘의 날씨입니다.", en: "Hello, here is today's weather." },
      { ko: "오늘 서울은 맑고 따뜻하겠습니다.", en: "Seoul will be clear and warm today." },
      { ko: "낮 최고 기온은 이십삼 도입니다.", en: "The daytime high is 23 degrees." },
      { ko: "저녁에는 비가 조금 오겠습니다.", en: "There will be a little rain in the evening." },
      { ko: "우산을 꼭 챙기세요!", en: "Be sure to take an umbrella!" },
    ],
  },
  {
    id: "c-directions",
    kind: "clip",
    title: "길 묻기",
    titleEn: "Asking for directions",
    topic: "Life",
    level: "A2",
    emoji: "🗺️",
    gradient: "from-violet-500 to-fuchsia-500",
    sentences: [
      { ko: "실례합니다.", en: "Excuse me.", speaker: "B" },
      { ko: "지하철역이 어디에 있어요?", en: "Where is the subway station?", speaker: "B" },
      { ko: "저기 은행 보이세요?", en: "Do you see that bank over there?", speaker: "A" },
      { ko: "네, 보여요.", en: "Yes, I see it.", speaker: "B" },
      { ko: "은행에서 왼쪽으로 가면 바로 있어요.", en: "Turn left at the bank and it's right there.", speaker: "A" },
      { ko: "감사합니다!", en: "Thank you!", speaker: "B" },
    ],
  },
  {
    id: "c-hangang",
    kind: "clip",
    title: "한강 브이로그",
    titleEn: "Han River vlog",
    topic: "Culture",
    level: "A2",
    emoji: "🍗",
    gradient: "from-cyan-500 to-blue-600",
    sentences: [
      { ko: "오늘은 친구랑 한강 공원에 왔어요.", en: "Today I came to Hangang Park with a friend." },
      { ko: "날씨가 정말 좋아요.", en: "The weather is really nice." },
      { ko: "우리는 치킨을 시켰어요.", en: "We ordered chicken." },
      { ko: "한강에서 먹는 치킨은 진짜 맛있어요.", en: "Chicken eaten by the Han River is really delicious." },
      { ko: "다음에 같이 올래요?", en: "Want to come with me next time?" },
    ],
  },
  {
    id: "c-subway-announcement",
    kind: "clip",
    title: "지하철 안내 방송",
    titleEn: "Subway announcement",
    topic: "Society",
    level: "A2",
    emoji: "🚉",
    gradient: "from-lime-500 to-green-700",
    sentences: [
      { ko: "이번 역은 강남, 강남역입니다.", en: "This stop is Gangnam, Gangnam Station." },
      { ko: "내리실 문은 오른쪽입니다.", en: "The doors will open on the right." },
      { ko: "2호선으로 갈아타실 고객께서는 이번 역에서 내리시기 바랍니다.", en: "Passengers transferring to Line 2, please get off at this station." },
      { ko: "내리실 때 물건을 꼭 챙기세요.", en: "Please be sure to take your belongings when you get off." },
    ],
  },
  {
    id: "c-kimbap",
    kind: "clip",
    title: "김밥 만들기",
    titleEn: "Making gimbap",
    topic: "Culture",
    level: "A2",
    emoji: "🍙",
    gradient: "from-orange-500 to-red-600",
    sentences: [
      { ko: "오늘은 김밥을 만들어 볼게요.", en: "Today I'll try making gimbap." },
      { ko: "먼저 밥에 참기름과 소금을 넣어요.", en: "First, add sesame oil and salt to the rice." },
      { ko: "김 위에 밥을 얇게 펴요.", en: "Spread the rice thinly on the seaweed." },
      { ko: "그리고 계란, 당근, 햄을 올려요.", en: "Then put egg, carrot and ham on top." },
      { ko: "꼭꼭 말아서 자르면 끝!", en: "Roll it tightly, slice it, and you're done!" },
    ],
  },
];
