/**
 * The learner's own Quizlet DLPT vocabulary (Korean DLPT 1–100, 101–200,
 * 201–300 and the first 100 lower-level terms), cleaned up: the first
 * slash variant is the answer, the others are accepted too, and the
 * original card text is kept in `full`.
 */
export interface BankTerm {
  ko: string;
  en: string;
  alt?: string[];
  full?: string;
}

export const DLPT_1_100: BankTerm[] = [
  { ko: "가격 인상", en: "price increase", alt: ["가격인상"] },
  { ko: "가격 인하", en: "price decrease", alt: ["가격인하"] },
  { ko: "가격 조정", en: "price adjustment", alt: ["가격조정"] },
  { ko: "가격변동", en: "price fluctuation" },
  { ko: "가로", en: "horizontally, width" },
  { ko: "세로", en: "height, length" },
  { ko: "수직", en: "being vertical, being straight" },
  { ko: "수평", en: "being flat/even, being horizontal" },
  { ko: "간암", en: "liver cancer" },
  { ko: "간판", en: "store sign" },
  { ko: "간호사", en: "nurse/to nurse", alt: ["간호하다"], full: "간호사/간호하다" },
  { ko: "갈색", en: "brown" },
  { ko: "갈아타다", en: "transfer" },
  { ko: "감상", en: "appreciation, sentimentality" },
  { ko: "감시하다", en: "observe/watch" },
  { ko: "강박감", en: "obsession" },
  { ko: "강의하다", en: "to lecture" },
  { ko: "강제로", en: "forcibly/coercively" },
  { ko: "강진", en: "strong earthquake" },
  { ko: "갖추다", en: "be equipped, be qualified" },
  { ko: "개막식", en: "opening ceremony" },
  { ko: "개발하다", en: "develop" },
  { ko: "자기 계발", en: "self-improvement", alt: ["자기계발"] },
  { ko: "개방하다", en: "open/be opened to the public", alt: ["개방되다"], full: "개방하다/개방되다" },
  { ko: "개업하다", en: "to open/start a business" },
  { ko: "개통하다", en: "open a service / open to traffic", alt: ["개통되다"], full: "개통하다/개통되다" },
  { ko: "객차", en: "passenger car/carriage" },
  { ko: "화물차", en: "cargo car/freight vehicle" },
  { ko: "거동이 불편하다", en: "have difficulty moving", alt: ["거동이불편하다"] },
  { ko: "거부하다", en: "refuse, reject / feeling of rejection", alt: ["거부감"], full: "거부하다/거부감" },
  { ko: "거주하다", en: "to reside, to dwell" },
  { ko: "거짓말 탐지기", en: "lie detector", alt: ["거짓말탐지기"] },
  { ko: "건강", en: "health (insurance/food/management)", full: "건강 (보험/식/관리)" },
  { ko: "건널목", en: "railroad crossing, crosswalk, crossing" },
  { ko: "검거하다", en: "to arrest, apprehend" },
  { ko: "작전", en: "tactic, strategy, operation" },
  { ko: "결과", en: "result/as a result", alt: ["결과적으로"], full: "결과/결과적으로" },
  { ko: "결식", en: "going without a meal / undernourished children", alt: ["결식아동"], full: "결식/결식아동" },
  { ko: "결핵", en: "tuberculosis (TB)" },
  { ko: "겸손하다", en: "to be humble" },
  { ko: "경고하다", en: "warn/warning", alt: ["경고문"], full: "경고하다/경고문" },
  { ko: "경기 회복", en: "economic recovery", alt: ["경기회복"] },
  { ko: "경기 불황", en: "economic recession", alt: ["경기불황"] },
  { ko: "경기 호황", en: "economic boom", alt: ["경기호황"] },
  { ko: "경상수지", en: "current balance" },
  { ko: "경위", en: "details, exact account" },
  { ko: "조사하다", en: "to investigate" },
  { ko: "연구하다", en: "to research, study" },
  { ko: "경향", en: "tendency, inclination" },
  { ko: "경험", en: "experience" },
  { ko: "경력", en: "career, work experience" },
  { ko: "계모", en: "stepmother/stepfather", alt: ["계부"], full: "계모/계부" },
  { ko: "계절", en: "season" },
  { ko: "계획하다", en: "to plan", alt: ["짜다", "만들다"], full: "계획하다/짜다/만들다" },
  { ko: "고도", en: "altitude/height", alt: ["높이"], full: "고도/높이" },
  { ko: "제한", en: "limit, restriction" },
  { ko: "고발하다", en: "to whistle-blow, to complain, to report" },
  { ko: "신고하다", en: "to report, to declare" },
  { ko: "고생스럽다", en: "suffering hardship/experience hardship", alt: ["고생하다"], full: "고생스럽다/고생하다" },
  { ko: "고소하다", en: "to accuse, to indict / nutty flavor" },
  { ko: "소송하다", en: "to file a lawsuit" },
  { ko: "고아원", en: "orphanage" },
  { ko: "고학력", en: "being highly educated" },
  { ko: "실업자", en: "unemployed person" },
  { ko: "골수", en: "bone marrow, depth of one's heart, the core/keypoint" },
  { ko: "공개하다", en: "reveal/open to the public" },
  { ko: "공고하다", en: "announce/announcement", alt: ["공고문"], full: "공고하다/공고문" },
  { ko: "공공장소", en: "public place" },
  { ko: "공급하다", en: "supply" },
  { ko: "공기오염", en: "air/atmospheric pollution", alt: ["대기오염"], full: "공기오염/대기오염" },
  { ko: "공기총", en: "air gun" },
  { ko: "공무원", en: "civil servant/public official", alt: ["공직자"], full: "공무원/공직자" },
  { ko: "공휴일", en: "public holiday" },
  { ko: "과반수", en: "more than half/majority" },
  { ko: "과수원", en: "orchard" },
  { ko: "과외", en: "private lesson" },
  { ko: "과외비", en: "private lesson fee/private education fee", alt: ["사교육비"], full: "과외비/사교육비" },
  { ko: "고액과외", en: "expensive private lessons" },
  { ko: "관광명소", en: "tourist attraction" },
  { ko: "관광비자", en: "tourist visa" },
  { ko: "관련되다", en: "involved with/related to" },
  { ko: "관리하다", en: "manage/management fee", alt: ["관리비"], full: "관리하다/관리비" },
  { ko: "관심", en: "interest" },
  { ko: "광우병", en: "mad cow disease" },
  { ko: "괴한", en: "suspicious/unidentified person" },
  { ko: "교권", en: "educational authority" },
  { ko: "교육열", en: "passion for education" },
  { ko: "교통 정체", en: "traffic congestion", alt: ["교통정체"] },
  { ko: "교통이 마비되다", en: "traffic gets paralyzed", alt: ["교통이마비되다"] },
  { ko: "구르다", en: "roll over" },
  { ko: "구속영장을 신청하다", en: "request arrest warrant", alt: ["구속영장을신청하다"] },
  { ko: "구입하다", en: "purchase" },
  { ko: "구조", en: "rescue (rescuer/activity/operation/squad)", full: "구조 (원/활동/작업/대)" },
  { ko: "구타", en: "beating (group)", full: "구타 (집단)" },
  { ko: "구토", en: "vomiting" },
  { ko: "구하다", en: "rescue/save" },
  { ko: "군견", en: "military dog" },
  { ko: "군사 분계선", en: "military demarcation line", alt: ["군사분계선"] },
  { ko: "권위", en: "authority/authoritative", full: "권위/적" },
  { ko: "귀금속", en: "precious metal" },
];

export const DLPT_101_200: BankTerm[] = [
  { ko: "기아", en: "famine, starvation" },
  { ko: "기피하다", en: "to avoid (due to great dislike)" },
  { ko: "기호", en: "liking/preference (product/food)", alt: ["선호"], full: "기호/선호 (품/식품)" },
  { ko: "기혼", en: "married" },
  { ko: "긴급 구조 활동", en: "emergency rescue operation", alt: ["긴급구조활동"] },
  { ko: "길조", en: "lucky sign, auspicious" },
  { ko: "꾸준히", en: "constantly, steadily" },
  { ko: "낙서", en: "graffiti/doodling" },
  { ko: "낙하산", en: "parachute" },
  { ko: "난동을 부리다", en: "cause a disturbance", alt: ["난동을부리다"] },
  { ko: "남매", en: "brother and sister (sibling)" },
  { ko: "남방", en: "southern/northern boundary", alt: ["북방 한계선"], full: "남방/북방 한계선" },
  { ko: "내륙 지방", en: "inland region", alt: ["내륙지방"] },
  { ko: "내복", en: "underwear" },
  { ko: "넉넉하다", en: "ample/sufficient/well-off", alt: ["여유 있다"], full: "넉넉하다/여유 있다" },
  { ko: "노동 집약적", en: "labor intensive", alt: ["노동집약적"] },
  { ko: "노무자", en: "laborer", alt: ["노동자"], full: "노무자/노동자" },
  { ko: "노사 협상", en: "labor-management negotiations", alt: ["노사협상"] },
  { ko: "노선", en: "route/line (subway/bus)", full: "노선 (지하철/버스)" },
  { ko: "노숙자", en: "homeless people" },
  { ko: "노출", en: "exposure (to be revealed)" },
  { ko: "농약", en: "agricultural pesticide" },
  { ko: "농장", en: "farm (fruit/weekend)", full: "농장 (과일/주말)" },
  { ko: "농협", en: "National Agricultural Cooperative Federation", full: "농협 (농업협동조합)" },
  { ko: "뇌물", en: "bribe" },
  { ko: "뇌졸증", en: "stroke" },
  { ko: "누명을 쓰다", en: "be falsely accused of (be cleared of a false accusation)", alt: ["누명을쓰다"], full: "누명을 쓰다 (벗다)" },
  { ko: "뉘우치다", en: "to feel remorse; to regret" },
  { ko: "다양하다", en: "various/diverse" },
  { ko: "단독", en: "single (solo flight/one on one talks)", full: "단독 (비행/회담)" },
  { ko: "단속하다", en: "to crack down on" },
  { ko: "단점", en: "disadvantage/weak point" },
  { ko: "단풍", en: "autumn foliage (excursion/viewing)", full: "단풍 (놀이/구경)" },
  { ko: "닮다", en: "to take after, resemble" },
  { ko: "당국", en: "authority (government/school)", full: "당국 (정부/학교)" },
  { ko: "당뇨병", en: "diabetes" },
  { ko: "당당하다", en: "confident, dignified" },
  { ko: "당부하다", en: "to ask, request" },
  { ko: "당선되다", en: "be elected" },
  { ko: "당연지사", en: "matter of course, natural result" },
  { ko: "대가", en: "compensation" },
  { ko: "대기 의자", en: "seat in waiting area", alt: ["대기의자"] },
  { ko: "대낮", en: "broad daylight" },
  { ko: "대마초", en: "marijuana" },
  { ko: "대상", en: "grand prize" },
  { ko: "대신하다", en: "to replace" },
  { ko: "대책", en: "(counter) measure (flood/drought/emergency/famine)", full: "대책 (수해/가뭄/긴급/기아)" },
  { ko: "대피하다", en: "to evacuate" },
  { ko: "대학원", en: "graduate school" },
  { ko: "대형화", en: "enlargement" },
  { ko: "덧붙이다", en: "to add on" },
  { ko: "도난 사건", en: "robbery (case/incident)", alt: ["도난사건"] },
  { ko: "도발하다", en: "to provoke" },
  { ko: "도움이 되다", en: "to be helpful", alt: ["도움이되다"] },
  { ko: "독신자", en: "unmarried person" },
  { ko: "돌변하다", en: "to change suddenly" },
  { ko: "돌아가다", en: "to pass away, to die", full: "돌아가다 (별세/타계/사망하다)" },
  { ko: "돕다", en: "to help, help", alt: ["도움"], full: "돕다/도움" },
  { ko: "동 서 해안", en: "( / )", alt: ["동서해안"] },
  { ko: "동기 동창", en: "student of same class year", alt: ["동기동창"] },
  { ko: "동시 통역", en: "simultaneous interpretation", alt: ["동시통역"] },
  { ko: "동의하다", en: "agree" },
  { ko: "동파하다", en: "to burst due to being frozen" },
  { ko: "두렵다", en: "to be scared", alt: ["두려워하다"], full: "두렵다/두려워하다" },
  { ko: "두통", en: "headache" },
  { ko: "등산 하다", en: "mountain (very high mountain) climbing", alt: ["등산하다"], full: "등산 (등반) 하다" },
  { ko: "때리다", en: "to hit/to beat", alt: ["구타하다"], full: "때리다/구타하다" },
  { ko: "떠내려가다", en: "float away/in", alt: ["오다"], full: "떠내려가다/오다" },
  { ko: "떼", en: "a large group of" },
  { ko: "떼죽음", en: "mass death/death of a group" },
  { ko: "뜨다", en: "float/take off/become famous" },
  { ko: "마르다", en: "dry" },
  { ko: "마비되다", en: "become paralyzed (whole body)", full: "마비되다 (전신이)" },
  { ko: "마술사", en: "magician" },
  { ko: "마약", en: "drug" },
  { ko: "막히다", en: "to be blocked" },
  { ko: "맞다", en: "correct/be struck/be beaten" },
  { ko: "맞이하다", en: "to greet/to welcome", alt: ["환영하다"], full: "맞이하다/환영하다" },
  { ko: "맞벌이 부부", en: "dual-income couple", alt: ["맞벌이부부"] },
  { ko: "맡기다", en: "entrust" },
  { ko: "매운 맛", en: "spicy taste", alt: ["매운맛"] },
  { ko: "매장", en: "store/burial" },
  { ko: "맥박", en: "pulse" },
  { ko: "맨", en: "bare (hand/foot/fist)", full: "맨(손/발/주먹)" },
  { ko: "머리방", en: "beauty salon" },
  { ko: "머리카락", en: "hair (of one's head)" },
  { ko: "머무르다", en: "to stay, remain", alt: ["머물다"], full: "머무르다/머물다" },
  { ko: "면도", en: "shaving (razor)", full: "면도(기)" },
  { ko: "면역", en: "immunity (system/level)", full: "면역(체계/력)" },
  { ko: "명퇴", en: "voluntary resignation/retirement", full: "명퇴 (명예퇴직)" },
  { ko: "모금", en: "fundraising (campaign/event)", full: "모금(운동/행사)" },
  { ko: "모금하다", en: "to raise money" },
  { ko: "모유", en: "mother's milk/to breastfeed", alt: ["모유를 먹이다"], full: "모유/모유를 먹이다" },
  { ko: "모집하다", en: "to recruit/recruiter", alt: ["모집관"], full: "모집하다/모집관" },
  { ko: "목격하다", en: "to witness/witness", alt: ["목격자"], full: "목격하다/목격자" },
  { ko: "목숨", en: "life (put one's life on the line/lose one's life)", full: "목숨 (걸다/잃다)" },
  { ko: "몰래", en: "secretly/stealthily", alt: ["모르게"], full: "몰래/모르게" },
  { ko: "무계획", en: "no planning, unplanned" },
  { ko: "무료", en: "free of charge", alt: ["공짜"], full: "무료/공짜" },
];

export const DLPT_201_300: BankTerm[] = [
  { ko: "무리하게", en: "unreasonably/irrationally" },
  { ko: "무역", en: "trade (competition/balance/friction)", full: "무역 (경제/수지/마찰)" },
  { ko: "무장하다", en: "arm (armed robber/strange armed person)", full: "무장하다 (강도/괴한)" },
  { ko: "문의하다", en: "inquiry (phone number)", full: "문의하다 (전화)" },
  { ko: "물가", en: "price (rise/hike/reduction/drop)", full: "물가 (인상/상승/인하/하락)" },
  { ko: "물놀이 사고", en: "water accident", alt: ["물놀이사고"] },
  { ko: "물에 빠지다", en: "fall into water", alt: ["물에빠지다"] },
  { ko: "물에 잠기다", en: "submerged under water", alt: ["물에잠기다"] },
  { ko: "물의를 빚다", en: "cause controversy/public criticism", alt: ["일으키다", "물의를빚다"], full: "물의를 빚다/일으키다" },
  { ko: "미끄러지다", en: "slip/slide" },
  { ko: "미술", en: "art (museum/exhibition/artistic)", full: "미술 (관/전시/적)" },
  { ko: "미아", en: "lost child" },
  { ko: "미전향 포로", en: "unconverted POW", alt: ["미전향포로"] },
  { ko: "민방위 훈련", en: "civil defense exercise", alt: ["민방위훈련"] },
  { ko: "밀매", en: "illicit sale/illicit smuggling organization", alt: ["밀매 조직"], full: "밀매/밀매 조직" },
  { ko: "밀수", en: "smuggling (goods/smuggler/organization)", full: "밀수 (품/범/조직)" },
  { ko: "반대", en: "opposing (direction/opinion/power)", full: "반대 (방향/의견/세력)" },
  { ko: "반도체 산업", en: "semiconductor industry", alt: ["반도체산업"] },
  { ko: "반응", en: "response" },
  { ko: "반환하다", en: "return" },
  { ko: "발견하다", en: "discover" },
  { ko: "발급하다", en: "issue (passport/license)", full: "발급하다 (여권/면허증)" },
  { ko: "발명", en: "invention (item/patent/inventor)", full: "발명 (품/특히/자)" },
  { ko: "발병률", en: "rate of disease occurence" },
  { ko: "발족하다", en: "establish/start (a committee/group)" },
  { ko: "밤 새다", en: "stay up all night long", alt: ["밤새다"], full: "밤(을) 새(우)다" },
  { ko: "방뇨", en: "urination" },
  { ko: "방안", en: "measure/plan", full: "방안/안" },
  { ko: "방송", en: "broadcast/telecast/televise", alt: ["방영하다"], full: "방송/방영하다" },
  { ko: "방지", en: "prevent", alt: ["예방하다"], full: "방지/예방하다" },
  { ko: "방화하다", en: "set on fire (arsonist/arson case/incident)", full: "방화하다 (방화범/방화사건)" },
  { ko: "배다른 형", en: "half older brother (from male point of view)/younger sibling/sibling", alt: ["동생", "형제", "배다른형"], full: "배다른 형/동생/형제" },
  { ko: "배달", en: "delivery (charge/vehicle)", full: "배달 (료/차)" },
  { ko: "배상", en: "compensation (money)", alt: ["보상"], full: "배상/보상 (금)" },
  { ko: "배우자", en: "spouse" },
  { ko: "배회하다", en: "loiter about/hang around/hover", alt: ["맴돌다"], full: "배회하다/맴돌다" },
  { ko: "백로", en: "white heron/egret" },
  { ko: "백혈병", en: "leukemia" },
  { ko: "벌금", en: "fine (monetary penalty)", full: "벌금 (형)" },
  { ko: "법", en: "law (net of the law)", full: "법 (망)" },
  { ko: "법을 준수하다", en: "abide by the law/obey the law", alt: ["지키다", "법을준수하다"], full: "법을 준수하다/지키다" },
  { ko: "벤처 기업", en: "venture business", alt: ["벤처기업"] },
  { ko: "변조", en: "forgery (counterfeit note/forged check)", alt: ["위조"], full: "변조/위조 (지폐/수표)" },
  { ko: "병력", en: "troop/military forces (mobilization/size)", full: "병력 (동원/규모)" },
  { ko: "보류하다", en: "hold off/reserve", alt: ["유보하다"], full: "보류하다/유보하다" },
  { ko: "보석 세공", en: "jewelry design", alt: ["보석세공"] },
  { ko: "보수", en: "conservative (party)", full: "보수 (당)" },
  { ko: "보조", en: "assistance (life assisting device/government subsidy)", full: "보조 (생명 장치/정부)" },
  { ko: "보청기", en: "hearing aid" },
  { ko: "보험", en: "insurance (premium/fraud)", full: "보험 (료/사기)" },
  { ko: "복용하다", en: "take medicine (internally)" },
  { ko: "복제", en: "cloning" },
  { ko: "복통", en: "stomachache" },
  { ko: "복학하다", en: "return to school" },
  { ko: "봉급", en: "salary/monthly salary/weekly pay", alt: ["월급", "주급"], full: "봉급/월급/주급" },
  { ko: "봉사", en: "service (volunteer)", full: "봉사 (자원)" },
  { ko: "부검", en: "autopsy" },
  { ko: "부유하다", en: "wealthy" },
  { ko: "부작용", en: "side effect" },
  { ko: "부적절하다", en: "inappropriate" },
  { ko: "부정", en: "wrongful/unrighteous/corrupt", full: "부정 (부패/입학/행위)" },
  { ko: "부족하다", en: "insufficient" },
  { ko: "부주의", en: "carelessness" },
  { ko: "분석하다", en: "analyze/analytic", full: "분석하다/적" },
  { ko: "분실", en: "loss (lost item)", full: "분실 (물)" },
  { ko: "분위기", en: "atmosphere" },
  { ko: "분유", en: "powdered milk" },
  { ko: "불구속 입건", en: "booking without restraint", alt: ["불구속입건"] },
  { ko: "불구자", en: "handicapped/disabled person", alt: ["장애인"], full: "불구자/장애인" },
  { ko: "불법", en: "illegal (behavior/sales/immigrant)", full: "불법 (행위/매매/체류자)" },
  { ko: "불볕더위", en: "scorching heat" },
  { ko: "불안", en: "(feeling of) insecurity/anxiety", full: "불안 (감)" },
  { ko: "불우 이웃", en: "neighbors in need", alt: ["불우이웃"] },
  { ko: "불 지르다", en: "set on fire", alt: ["방화하다", "불지르다"], full: "불(을) 지르다/방화하다" },
  { ko: "불편을 겪다", en: "experience incovenience", alt: ["불편을겪다"] },
  { ko: "불평하다", en: "complain" },
  { ko: "붐비다", en: "crowded" },
  { ko: "붕괴되다", en: "collapse", alt: ["무너지다"], full: "붕괴되다/무너지다" },
  { ko: "비닐 봉지", en: "vinyl/plastic bag", alt: ["비닐봉지"] },
  { ko: "비리", en: "inappropriate/illegal action/behavior (election/military)", full: "비리 (선거/병무/경리)" },
  { ko: "비만아", en: "obese child" },
  { ko: "비상", en: "emergency (escape equipment/landing)", full: "비상 (탈출 장치/착륙)" },
  { ko: "비수기", en: "non-demanding season/high-demanding season", alt: ["성수기"], full: "비수기/성수기" },
  { ko: "비율", en: "ratio/proportion" },
  { ko: "비축 식량", en: "stockpiled food", alt: ["비축식량"] },
  { ko: "비흡연자", en: "non-smoker/smoker", alt: ["흡연자"], full: "비흡연자/흡연자" },
  { ko: "빌리다", en: "borrow/lend", alt: ["빌려주다"], full: "빌리다/빌려주다" },
  { ko: "빙판길", en: "icy road" },
  { ko: "빚을 갚다", en: "repay a debt", alt: ["빚을갚다"] },
  { ko: "빼앗다", en: "take something by force", alt: ["강탈하다"], full: "빼앗다/강탈하다" },
  { ko: "뺑소니", en: "hit and run (car/driver)", full: "뺑소니 (차/운전사)" },
  { ko: "뼈", en: "bone" },
  { ko: "사복", en: "civilian clothes (in/wearing)", full: "사복 (차림/착용)" },
  { ko: "사체", en: "dead body/corpse", alt: ["시체"], full: "사체/시체" },
  { ko: "사치품", en: "luxury goods" },
  { ko: "사회", en: "society (organization/issues/activities)", full: "사회 (단체/문제/활동)" },
  { ko: "산림", en: "forest (conservancy/policy)", full: "산림 (보호/정책)" },
  { ko: "산모", en: "mother" },
  { ko: "산보", en: "take a walk", alt: ["산책하다"], full: "산보/산책하다" },
  { ko: "살신 성인", en: "act of benevolence through self-sacrifice", alt: ["살신성인"] },
];

export const DLPT_LOWER: BankTerm[] = [
  { ko: "가격인상", en: "price hike" },
  { ko: "가격인하", en: "price drop" },
  { ko: "가격조정", en: "price adjustment" },
  { ko: "가격변동", en: "price change" },
  { ko: "가로", en: "width" },
  { ko: "세로", en: "length" },
  { ko: "가죽", en: "leather" },
  { ko: "간암", en: "liver cancer" },
  { ko: "간판", en: "(store) sign" },
  { ko: "간호사", en: "a nurse" },
  { ko: "간호하다", en: "to nurse" },
  { ko: "갈색", en: "brown" },
  { ko: "갈아타다", en: "to transfer" },
  { ko: "감상하다", en: "to appreciate (music/art)" },
  { ko: "감시하다", en: "to keep a watchful eye on" },
  { ko: "강박감", en: "obsession" },
  { ko: "강의하다", en: "to lecture" },
  { ko: "강제로", en: "forcibly" },
  { ko: "강진", en: "strong earthquake" },
  { ko: "갖추다", en: "to have/be equipped with" },
  { ko: "개막식", en: "opening ceremony" },
  { ko: "개발하다", en: "to develop" },
  { ko: "개방하다", en: "to open/be opened", alt: ["개방되다"], full: "개방하다/개방되다" },
  { ko: "개업하다", en: "to open a business" },
  { ko: "개통하다", en: "to be open to traffic", alt: ["개통되다"], full: "개통하다/개통되다" },
  { ko: "객차", en: "passenger car" },
  { ko: "화물차", en: "cargo train" },
  { ko: "거동이 불편하다", en: "to have difficulty moving", alt: ["거동이불편하다"] },
  { ko: "거부하다", en: "to refuse" },
  { ko: "거부감", en: "feeling of rejection" },
  { ko: "거주하다", en: "to reside" },
  { ko: "거짓말 탐지기", en: "lie detector", alt: ["거짓말탐지기"] },
  { ko: "건강보험", en: "health insurance" },
  { ko: "건강식", en: "healthfood" },
  { ko: "건강관리", en: "health management" },
  { ko: "건널목", en: "crossing" },
  { ko: "검거하다", en: "to arrest" },
  { ko: "검거 작전", en: "arrest operation", alt: ["검거작전"] },
  { ko: "결과", en: "result" },
  { ko: "결과적으로", en: "as a result" },
  { ko: "결식", en: "going without a meal" },
  { ko: "결식아동 돕기", en: "helping undernourished children", alt: ["결식아동돕기"] },
  { ko: "결핵", en: "tuberculosis(eradication)", full: "결핵(퇴치)" },
  { ko: "겸손하다", en: "to be humble" },
  { ko: "경고하다", en: "to warn" },
  { ko: "경고문", en: "a warning" },
  { ko: "경기회복", en: "economic recovery" },
  { ko: "경기불황", en: "economic recession" },
  { ko: "경기호황", en: "economic boom" },
  { ko: "경상수지", en: "trade balance" },
  { ko: "경위를 조사하다", en: "examine the details", alt: ["경위를조사하다"] },
  { ko: "경향", en: "tendency/trend" },
  { ko: "경험", en: "experience" },
  { ko: "경력", en: "career" },
  { ko: "계모", en: "stepmother" },
  { ko: "계절", en: "season" },
  { ko: "계획하다", en: "to plan" },
  { ko: "계획짜다", en: "to plan" },
  { ko: "계획만들다", en: "to plan" },
  { ko: "고도", en: "altitude/height restriction", alt: ["높이"], full: "고도/높이(제한)" },
  { ko: "고발하다", en: "to report (to the authorities)" },
  { ko: "신고하다", en: "to report (to the authorities)" },
  { ko: "고생스럽다", en: "to be hard to bear, tough" },
  { ko: "고생하다", en: "to experience hardship" },
  { ko: "고소하다", en: "to sue, bring a suit against" },
  { ko: "고아원", en: "orphanage" },
  { ko: "고학력 실업자", en: "highly-educated and unemployed", alt: ["고학력실업자"] },
  { ko: "골수", en: "bone marrow" },
  { ko: "공개하다", en: "to reveal/ to open to the public" },
  { ko: "공고하다", en: "to publicly announce" },
  { ko: "공고문", en: "an announcement" },
  { ko: "공공장소", en: "public place" },
  { ko: "공급하다", en: "to supply" },
  { ko: "공기오염", en: "air pollution" },
  { ko: "대기오염", en: "air pollution" },
  { ko: "공기총", en: "air gun" },
  { ko: "공무원", en: "public servant" },
  { ko: "공직자", en: "public official" },
  { ko: "공휴일", en: "public holiday" },
  { ko: "과반수", en: "more than half/majority" },
  { ko: "과수원", en: "orchard" },
  { ko: "과외", en: "extracurricular private tutoring/teaching" },
  { ko: "과외비", en: "private tutoring fee" },
  { ko: "사교육비", en: "private tutoring fee" },
  { ko: "고액과외", en: "expensive off-campus tutoring" },
  { ko: "관광명소", en: "tourist attraction" },
  { ko: "관광비자", en: "tourist visa" },
  { ko: "관련되다", en: "to be involved with/related" },
  { ko: "관리하다", en: "to manage" },
  { ko: "관리비", en: "management fee" },
  { ko: "관심", en: "interest/concern" },
  { ko: "광우병", en: "mad cow disease" },
  { ko: "괴한", en: "suspicious/unidentified person" },
  { ko: "교권", en: "teacher's authority" },
  { ko: "교육열", en: "enthusiasm for education" },
  { ko: "교통 정체", en: "traffic congestion/standstill", alt: ["교통정체"] },
  { ko: "교통이 마비되다", en: "severe traffic jam", alt: ["교통이마비되다"] },
  { ko: "구르다", en: "to roll over, flip over" },
  { ko: "구속영장을 신청하다", en: "to request an arrest warrant", alt: ["구속영장을신청하다"] },
  { ko: "구입하다", en: "to purchase" },
];
