/**
 * The learner's own Quizlet DLPT vocabulary (Korean DLPT 1–800 and the first 100 lower-level terms), cleaned up: the first
 * slash variant is the answer, the others are accepted too, and the
 * original card text is kept in `full`.
 */
export interface BankTerm {
  ko: string;
  en: string;
  alt?: string[];
  full?: string;
}

export const DLPT_1_100: BankTerm[] = [
  { ko: "가격 인상", en: "price increase", alt: ["가격인상"] },
  { ko: "가격 인하", en: "price decrease", alt: ["가격인하"] },
  { ko: "가격 조정", en: "price adjustment", alt: ["가격조정"] },
  { ko: "가격변동", en: "price fluctuation" },
  { ko: "가로", en: "horizontally, width" },
  { ko: "세로", en: "height, length" },
  { ko: "수직", en: "being vertical, being straight" },
  { ko: "수평", en: "being flat/even, being horizontal" },
  { ko: "간암", en: "liver cancer" },
  { ko: "간판", en: "store sign" },
  { ko: "간호사", en: "nurse/to nurse", alt: ["간호하다"], full: "간호사/간호하다" },
  { ko: "갈색", en: "brown" },
  { ko: "갈아타다", en: "transfer" },
  { ko: "감상", en: "appreciation, sentimentality" },
  { ko: "감시하다", en: "observe/watch" },
  { ko: "강박감", en: "obsession" },
  { ko: "강의하다", en: "to lecture" },
  { ko: "강제로", en: "forcibly/coercively" },
  { ko: "강진", en: "strong earthquake" },
  { ko: "갖추다", en: "be equipped, be qualified" },
  { ko: "개막식", en: "opening ceremony" },
  { ko: "개발하다", en: "develop" },
  { ko: "자기 계발", en: "self-improvement", alt: ["자기계발"] },
  { ko: "개방하다", en: "open/be opened to the public", alt: ["개방되다"], full: "개방하다/개방되다" },
  { ko: "개업하다", en: "to open/start a business" },
  { ko: "개통하다", en: "open a service / open to traffic", alt: ["개통되다"], full: "개통하다/개통되다" },
  { ko: "객차", en: "passenger car/carriage" },
  { ko: "화물차", en: "cargo car/freight vehicle" },
  { ko: "거동이 불편하다", en: "have difficulty moving", alt: ["거동이불편하다"] },
  { ko: "거부하다", en: "refuse, reject / feeling of rejection", alt: ["거부감"], full: "거부하다/거부감" },
  { ko: "거주하다", en: "to reside, to dwell" },
  { ko: "거짓말 탐지기", en: "lie detector", alt: ["거짓말탐지기"] },
  { ko: "건강", en: "health (insurance/food/management)", full: "건강 (보험/식/관리)" },
  { ko: "건널목", en: "railroad crossing, crosswalk, crossing" },
  { ko: "검거하다", en: "to arrest, apprehend" },
  { ko: "작전", en: "tactic, strategy, operation" },
  { ko: "결과", en: "result/as a result", alt: ["결과적으로"], full: "결과/결과적으로" },
  { ko: "결식", en: "going without a meal / undernourished children", alt: ["결식아동"], full: "결식/결식아동" },
  { ko: "결핵", en: "tuberculosis (TB)" },
  { ko: "겸손하다", en: "to be humble" },
  { ko: "경고하다", en: "warn/warning", alt: ["경고문"], full: "경고하다/경고문" },
  { ko: "경기 회복", en: "economic recovery", alt: ["경기회복"] },
  { ko: "경기 불황", en: "economic recession", alt: ["경기불황"] },
  { ko: "경기 호황", en: "economic boom", alt: ["경기호황"] },
  { ko: "경상수지", en: "current balance" },
  { ko: "경위", en: "details, exact account" },
  { ko: "조사하다", en: "to investigate" },
  { ko: "연구하다", en: "to research, study" },
  { ko: "경향", en: "tendency, inclination" },
  { ko: "경험", en: "experience" },
  { ko: "경력", en: "career, work experience" },
  { ko: "계모", en: "stepmother/stepfather", alt: ["계부"], full: "계모/계부" },
  { ko: "계절", en: "season" },
  { ko: "계획하다", en: "to plan", alt: ["짜다", "만들다"], full: "계획하다/짜다/만들다" },
  { ko: "고도", en: "altitude/height", alt: ["높이"], full: "고도/높이" },
  { ko: "제한", en: "limit, restriction" },
  { ko: "고발하다", en: "to whistle-blow, to complain, to report" },
  { ko: "신고하다", en: "to report, to declare" },
  { ko: "고생스럽다", en: "suffering hardship/experience hardship", alt: ["고생하다"], full: "고생스럽다/고생하다" },
  { ko: "고소하다", en: "to accuse, to indict / nutty flavor" },
  { ko: "소송하다", en: "to file a lawsuit" },
  { ko: "고아원", en: "orphanage" },
  { ko: "고학력", en: "being highly educated" },
  { ko: "실업자", en: "unemployed person" },
  { ko: "골수", en: "bone marrow, depth of one's heart, the core/keypoint" },
  { ko: "공개하다", en: "reveal/open to the public" },
  { ko: "공고하다", en: "announce/announcement", alt: ["공고문"], full: "공고하다/공고문" },
  { ko: "공공장소", en: "public place" },
  { ko: "공급하다", en: "supply" },
  { ko: "공기오염", en: "air/atmospheric pollution", alt: ["대기오염"], full: "공기오염/대기오염" },
  { ko: "공기총", en: "air gun" },
  { ko: "공무원", en: "civil servant/public official", alt: ["공직자"], full: "공무원/공직자" },
  { ko: "공휴일", en: "public holiday" },
  { ko: "과반수", en: "more than half/majority" },
  { ko: "과수원", en: "orchard" },
  { ko: "과외", en: "private lesson" },
  { ko: "과외비", en: "private lesson fee/private education fee", alt: ["사교육비"], full: "과외비/사교육비" },
  { ko: "고액과외", en: "expensive private lessons" },
  { ko: "관광명소", en: "tourist attraction" },
  { ko: "관광비자", en: "tourist visa" },
  { ko: "관련되다", en: "involved with/related to" },
  { ko: "관리하다", en: "manage/management fee", alt: ["관리비"], full: "관리하다/관리비" },
  { ko: "관심", en: "interest" },
  { ko: "광우병", en: "mad cow disease" },
  { ko: "괴한", en: "suspicious/unidentified person" },
  { ko: "교권", en: "educational authority" },
  { ko: "교육열", en: "passion for education" },
  { ko: "교통 정체", en: "traffic congestion", alt: ["교통정체"] },
  { ko: "교통이 마비되다", en: "traffic gets paralyzed", alt: ["교통이마비되다"] },
  { ko: "구르다", en: "roll over" },
  { ko: "구속영장을 신청하다", en: "request arrest warrant", alt: ["구속영장을신청하다"] },
  { ko: "구입하다", en: "purchase" },
  { ko: "구조", en: "rescue (rescuer/activity/operation/squad)", full: "구조 (원/활동/작업/대)" },
  { ko: "구타", en: "beating (group)", full: "구타 (집단)" },
  { ko: "구토", en: "vomiting" },
  { ko: "구하다", en: "rescue/save" },
  { ko: "군견", en: "military dog" },
  { ko: "군사 분계선", en: "military demarcation line", alt: ["군사분계선"] },
  { ko: "권위", en: "authority/authoritative", full: "권위/적" },
  { ko: "귀금속", en: "precious metal" },
];

export const DLPT_101_200: BankTerm[] = [
  { ko: "기아", en: "famine, starvation" },
  { ko: "기피하다", en: "to avoid (due to great dislike)" },
  { ko: "기호", en: "liking/preference (product/food)", alt: ["선호"], full: "기호/선호 (품/식품)" },
  { ko: "기혼", en: "married" },
  { ko: "긴급 구조 활동", en: "emergency rescue operation", alt: ["긴급구조활동"] },
  { ko: "길조", en: "lucky sign, auspicious" },
  { ko: "꾸준히", en: "constantly, steadily" },
  { ko: "낙서", en: "graffiti/doodling" },
  { ko: "낙하산", en: "parachute" },
  { ko: "난동을 부리다", en: "cause a disturbance", alt: ["난동을부리다"] },
  { ko: "남매", en: "brother and sister (sibling)" },
  { ko: "남방", en: "southern/northern boundary", alt: ["북방 한계선"], full: "남방/북방 한계선" },
  { ko: "내륙 지방", en: "inland region", alt: ["내륙지방"] },
  { ko: "내복", en: "underwear" },
  { ko: "넉넉하다", en: "ample/sufficient/well-off", alt: ["여유 있다"], full: "넉넉하다/여유 있다" },
  { ko: "노동 집약적", en: "labor intensive", alt: ["노동집약적"] },
  { ko: "노무자", en: "laborer", alt: ["노동자"], full: "노무자/노동자" },
  { ko: "노사 협상", en: "labor-management negotiations", alt: ["노사협상"] },
  { ko: "노선", en: "route/line (subway/bus)", full: "노선 (지하철/버스)" },
  { ko: "노숙자", en: "homeless people" },
  { ko: "노출", en: "exposure (to be revealed)" },
  { ko: "농약", en: "agricultural pesticide" },
  { ko: "농장", en: "farm (fruit/weekend)", full: "농장 (과일/주말)" },
  { ko: "농협", en: "National Agricultural Cooperative Federation", full: "농협 (농업협동조합)" },
  { ko: "뇌물", en: "bribe" },
  { ko: "뇌졸증", en: "stroke" },
  { ko: "누명을 쓰다", en: "be falsely accused of (be cleared of a false accusation)", alt: ["누명을쓰다"], full: "누명을 쓰다 (벗다)" },
  { ko: "뉘우치다", en: "to feel remorse; to regret" },
  { ko: "다양하다", en: "various/diverse" },
  { ko: "단독", en: "single (solo flight/one on one talks)", full: "단독 (비행/회담)" },
  { ko: "단속하다", en: "to crack down on" },
  { ko: "단점", en: "disadvantage/weak point" },
  { ko: "단풍", en: "autumn foliage (excursion/viewing)", full: "단풍 (놀이/구경)" },
  { ko: "닮다", en: "to take after, resemble" },
  { ko: "당국", en: "authority (government/school)", full: "당국 (정부/학교)" },
  { ko: "당뇨병", en: "diabetes" },
  { ko: "당당하다", en: "confident, dignified" },
  { ko: "당부하다", en: "to ask, request" },
  { ko: "당선되다", en: "be elected" },
  { ko: "당연지사", en: "matter of course, natural result" },
  { ko: "대가", en: "compensation" },
  { ko: "대기 의자", en: "seat in waiting area", alt: ["대기의자"] },
  { ko: "대낮", en: "broad daylight" },
  { ko: "대마초", en: "marijuana" },
  { ko: "대상", en: "grand prize" },
  { ko: "대신하다", en: "to replace" },
  { ko: "대책", en: "(counter) measure (flood/drought/emergency/famine)", full: "대책 (수해/가뭄/긴급/기아)" },
  { ko: "대피하다", en: "to evacuate" },
  { ko: "대학원", en: "graduate school" },
  { ko: "대형화", en: "enlargement" },
  { ko: "덧붙이다", en: "to add on" },
  { ko: "도난 사건", en: "robbery (case/incident)", alt: ["도난사건"] },
  { ko: "도발하다", en: "to provoke" },
  { ko: "도움이 되다", en: "to be helpful", alt: ["도움이되다"] },
  { ko: "독신자", en: "unmarried person" },
  { ko: "돌변하다", en: "to change suddenly" },
  { ko: "돌아가다", en: "to pass away, to die", full: "돌아가다 (별세/타계/사망하다)" },
  { ko: "돕다", en: "to help, help", alt: ["도움"], full: "돕다/도움" },
  { ko: "동 서 해안", en: "( / )", alt: ["동서해안"] },
  { ko: "동기 동창", en: "student of same class year", alt: ["동기동창"] },
  { ko: "동시 통역", en: "simultaneous interpretation", alt: ["동시통역"] },
  { ko: "동의하다", en: "agree" },
  { ko: "동파하다", en: "to burst due to being frozen" },
  { ko: "두렵다", en: "to be scared", alt: ["두려워하다"], full: "두렵다/두려워하다" },
  { ko: "두통", en: "headache" },
  { ko: "등산 하다", en: "mountain (very high mountain) climbing", alt: ["등산하다"], full: "등산 (등반) 하다" },
  { ko: "때리다", en: "to hit/to beat", alt: ["구타하다"], full: "때리다/구타하다" },
  { ko: "떠내려가다", en: "float away/in", alt: ["오다"], full: "떠내려가다/오다" },
  { ko: "떼", en: "a large group of" },
  { ko: "떼죽음", en: "mass death/death of a group" },
  { ko: "뜨다", en: "float/take off/become famous" },
  { ko: "마르다", en: "dry" },
  { ko: "마비되다", en: "become paralyzed (whole body)", full: "마비되다 (전신이)" },
  { ko: "마술사", en: "magician" },
  { ko: "마약", en: "drug" },
  { ko: "막히다", en: "to be blocked" },
  { ko: "맞다", en: "correct/be struck/be beaten" },
  { ko: "맞이하다", en: "to greet/to welcome", alt: ["환영하다"], full: "맞이하다/환영하다" },
  { ko: "맞벌이 부부", en: "dual-income couple", alt: ["맞벌이부부"] },
  { ko: "맡기다", en: "entrust" },
  { ko: "매운 맛", en: "spicy taste", alt: ["매운맛"] },
  { ko: "매장", en: "store/burial" },
  { ko: "맥박", en: "pulse" },
  { ko: "맨", en: "bare (hand/foot/fist)", full: "맨(손/발/주먹)" },
  { ko: "머리방", en: "beauty salon" },
  { ko: "머리카락", en: "hair (of one's head)" },
  { ko: "머무르다", en: "to stay, remain", alt: ["머물다"], full: "머무르다/머물다" },
  { ko: "면도", en: "shaving (razor)", full: "면도(기)" },
  { ko: "면역", en: "immunity (system/level)", full: "면역(체계/력)" },
  { ko: "명퇴", en: "voluntary resignation/retirement", full: "명퇴 (명예퇴직)" },
  { ko: "모금", en: "fundraising (campaign/event)", full: "모금(운동/행사)" },
  { ko: "모금하다", en: "to raise money" },
  { ko: "모유", en: "mother's milk/to breastfeed", alt: ["모유를 먹이다"], full: "모유/모유를 먹이다" },
  { ko: "모집하다", en: "to recruit/recruiter", alt: ["모집관"], full: "모집하다/모집관" },
  { ko: "목격하다", en: "to witness/witness", alt: ["목격자"], full: "목격하다/목격자" },
  { ko: "목숨", en: "life (put one's life on the line/lose one's life)", full: "목숨 (걸다/잃다)" },
  { ko: "몰래", en: "secretly/stealthily", alt: ["모르게"], full: "몰래/모르게" },
  { ko: "무계획", en: "no planning, unplanned" },
  { ko: "무료", en: "free of charge", alt: ["공짜"], full: "무료/공짜" },
];

export const DLPT_201_300: BankTerm[] = [
  { ko: "무리하게", en: "unreasonably/irrationally" },
  { ko: "무역", en: "trade (competition/balance/friction)", full: "무역 (경제/수지/마찰)" },
  { ko: "무장하다", en: "arm (armed robber/strange armed person)", full: "무장하다 (강도/괴한)" },
  { ko: "문의하다", en: "inquiry (phone number)", full: "문의하다 (전화)" },
  { ko: "물가", en: "price (rise/hike/reduction/drop)", full: "물가 (인상/상승/인하/하락)" },
  { ko: "물놀이 사고", en: "water accident", alt: ["물놀이사고"] },
  { ko: "물에 빠지다", en: "fall into water", alt: ["물에빠지다"] },
  { ko: "물에 잠기다", en: "submerged under water", alt: ["물에잠기다"] },
  { ko: "물의를 빚다", en: "cause controversy/public criticism", alt: ["일으키다", "물의를빚다"], full: "물의를 빚다/일으키다" },
  { ko: "미끄러지다", en: "slip/slide" },
  { ko: "미술", en: "art (museum/exhibition/artistic)", full: "미술 (관/전시/적)" },
  { ko: "미아", en: "lost child" },
  { ko: "미전향 포로", en: "unconverted POW", alt: ["미전향포로"] },
  { ko: "민방위 훈련", en: "civil defense exercise", alt: ["민방위훈련"] },
  { ko: "밀매", en: "illicit sale/illicit smuggling organization", alt: ["밀매 조직"], full: "밀매/밀매 조직" },
  { ko: "밀수", en: "smuggling (goods/smuggler/organization)", full: "밀수 (품/범/조직)" },
  { ko: "반대", en: "opposing (direction/opinion/power)", full: "반대 (방향/의견/세력)" },
  { ko: "반도체 산업", en: "semiconductor industry", alt: ["반도체산업"] },
  { ko: "반응", en: "response" },
  { ko: "반환하다", en: "return" },
  { ko: "발견하다", en: "discover" },
  { ko: "발급하다", en: "issue (passport/license)", full: "발급하다 (여권/면허증)" },
  { ko: "발명", en: "invention (item/patent/inventor)", full: "발명 (품/특히/자)" },
  { ko: "발병률", en: "rate of disease occurence" },
  { ko: "발족하다", en: "establish/start (a committee/group)" },
  { ko: "밤 새다", en: "stay up all night long", alt: ["밤새다"], full: "밤(을) 새(우)다" },
  { ko: "방뇨", en: "urination" },
  { ko: "방안", en: "measure/plan", full: "방안/안" },
  { ko: "방송", en: "broadcast/telecast/televise", alt: ["방영하다"], full: "방송/방영하다" },
  { ko: "방지", en: "prevent", alt: ["예방하다"], full: "방지/예방하다" },
  { ko: "방화하다", en: "set on fire (arsonist/arson case/incident)", full: "방화하다 (방화범/방화사건)" },
  { ko: "배다른 형", en: "half older brother (from male point of view)/younger sibling/sibling", alt: ["동생", "형제", "배다른형"], full: "배다른 형/동생/형제" },
  { ko: "배달", en: "delivery (charge/vehicle)", full: "배달 (료/차)" },
  { ko: "배상", en: "compensation (money)", alt: ["보상"], full: "배상/보상 (금)" },
  { ko: "배우자", en: "spouse" },
  { ko: "배회하다", en: "loiter about/hang around/hover", alt: ["맴돌다"], full: "배회하다/맴돌다" },
  { ko: "백로", en: "white heron/egret" },
  { ko: "백혈병", en: "leukemia" },
  { ko: "벌금", en: "fine (monetary penalty)", full: "벌금 (형)" },
  { ko: "법", en: "law (net of the law)", full: "법 (망)" },
  { ko: "법을 준수하다", en: "abide by the law/obey the law", alt: ["지키다", "법을준수하다"], full: "법을 준수하다/지키다" },
  { ko: "벤처 기업", en: "venture business", alt: ["벤처기업"] },
  { ko: "변조", en: "forgery (counterfeit note/forged check)", alt: ["위조"], full: "변조/위조 (지폐/수표)" },
  { ko: "병력", en: "troop/military forces (mobilization/size)", full: "병력 (동원/규모)" },
  { ko: "보류하다", en: "hold off/reserve", alt: ["유보하다"], full: "보류하다/유보하다" },
  { ko: "보석 세공", en: "jewelry design", alt: ["보석세공"] },
  { ko: "보수", en: "conservative (party)", full: "보수 (당)" },
  { ko: "보조", en: "assistance (life assisting device/government subsidy)", full: "보조 (생명 장치/정부)" },
  { ko: "보청기", en: "hearing aid" },
  { ko: "보험", en: "insurance (premium/fraud)", full: "보험 (료/사기)" },
  { ko: "복용하다", en: "take medicine (internally)" },
  { ko: "복제", en: "cloning" },
  { ko: "복통", en: "stomachache" },
  { ko: "복학하다", en: "return to school" },
  { ko: "봉급", en: "salary/monthly salary/weekly pay", alt: ["월급", "주급"], full: "봉급/월급/주급" },
  { ko: "봉사", en: "service (volunteer)", full: "봉사 (자원)" },
  { ko: "부검", en: "autopsy" },
  { ko: "부유하다", en: "wealthy" },
  { ko: "부작용", en: "side effect" },
  { ko: "부적절하다", en: "inappropriate" },
  { ko: "부정", en: "wrongful/unrighteous/corrupt", full: "부정 (부패/입학/행위)" },
  { ko: "부족하다", en: "insufficient" },
  { ko: "부주의", en: "carelessness" },
  { ko: "분석하다", en: "analyze/analytic", full: "분석하다/적" },
  { ko: "분실", en: "loss (lost item)", full: "분실 (물)" },
  { ko: "분위기", en: "atmosphere" },
  { ko: "분유", en: "powdered milk" },
  { ko: "불구속 입건", en: "booking without restraint", alt: ["불구속입건"] },
  { ko: "불구자", en: "handicapped/disabled person", alt: ["장애인"], full: "불구자/장애인" },
  { ko: "불법", en: "illegal (behavior/sales/immigrant)", full: "불법 (행위/매매/체류자)" },
  { ko: "불볕더위", en: "scorching heat" },
  { ko: "불안", en: "(feeling of) insecurity/anxiety", full: "불안 (감)" },
  { ko: "불우 이웃", en: "neighbors in need", alt: ["불우이웃"] },
  { ko: "불 지르다", en: "set on fire", alt: ["방화하다", "불지르다"], full: "불(을) 지르다/방화하다" },
  { ko: "불편을 겪다", en: "experience incovenience", alt: ["불편을겪다"] },
  { ko: "불평하다", en: "complain" },
  { ko: "붐비다", en: "crowded" },
  { ko: "붕괴되다", en: "collapse", alt: ["무너지다"], full: "붕괴되다/무너지다" },
  { ko: "비닐 봉지", en: "vinyl/plastic bag", alt: ["비닐봉지"] },
  { ko: "비리", en: "inappropriate/illegal action/behavior (election/military)", full: "비리 (선거/병무/경리)" },
  { ko: "비만아", en: "obese child" },
  { ko: "비상", en: "emergency (escape equipment/landing)", full: "비상 (탈출 장치/착륙)" },
  { ko: "비수기", en: "non-demanding season/high-demanding season", alt: ["성수기"], full: "비수기/성수기" },
  { ko: "비율", en: "ratio/proportion" },
  { ko: "비축 식량", en: "stockpiled food", alt: ["비축식량"] },
  { ko: "비흡연자", en: "non-smoker/smoker", alt: ["흡연자"], full: "비흡연자/흡연자" },
  { ko: "빌리다", en: "borrow/lend", alt: ["빌려주다"], full: "빌리다/빌려주다" },
  { ko: "빙판길", en: "icy road" },
  { ko: "빚을 갚다", en: "repay a debt", alt: ["빚을갚다"] },
  { ko: "빼앗다", en: "take something by force", alt: ["강탈하다"], full: "빼앗다/강탈하다" },
  { ko: "뺑소니", en: "hit and run (car/driver)", full: "뺑소니 (차/운전사)" },
  { ko: "뼈", en: "bone" },
  { ko: "사복", en: "civilian clothes (in/wearing)", full: "사복 (차림/착용)" },
  { ko: "사체", en: "dead body/corpse", alt: ["시체"], full: "사체/시체" },
  { ko: "사치품", en: "luxury goods" },
  { ko: "사회", en: "society (organization/issues/activities)", full: "사회 (단체/문제/활동)" },
  { ko: "산림", en: "forest (conservancy/policy)", full: "산림 (보호/정책)" },
  { ko: "산모", en: "mother" },
  { ko: "산보", en: "take a walk", alt: ["산책하다"], full: "산보/산책하다" },
  { ko: "살신 성인", en: "act of benevolence through self-sacrifice", alt: ["살신성인"] },
];

export const DLPT_LOWER: BankTerm[] = [
  { ko: "가격인상", en: "price hike" },
  { ko: "가격인하", en: "price drop" },
  { ko: "가격조정", en: "price adjustment" },
  { ko: "가격변동", en: "price change" },
  { ko: "가로", en: "width" },
  { ko: "세로", en: "length" },
  { ko: "가죽", en: "leather" },
  { ko: "간암", en: "liver cancer" },
  { ko: "간판", en: "(store) sign" },
  { ko: "간호사", en: "a nurse" },
  { ko: "간호하다", en: "to nurse" },
  { ko: "갈색", en: "brown" },
  { ko: "갈아타다", en: "to transfer" },
  { ko: "감상하다", en: "to appreciate (music/art)" },
  { ko: "감시하다", en: "to keep a watchful eye on" },
  { ko: "강박감", en: "obsession" },
  { ko: "강의하다", en: "to lecture" },
  { ko: "강제로", en: "forcibly" },
  { ko: "강진", en: "strong earthquake" },
  { ko: "갖추다", en: "to have/be equipped with" },
  { ko: "개막식", en: "opening ceremony" },
  { ko: "개발하다", en: "to develop" },
  { ko: "개방하다", en: "to open/be opened", alt: ["개방되다"], full: "개방하다/개방되다" },
  { ko: "개업하다", en: "to open a business" },
  { ko: "개통하다", en: "to be open to traffic", alt: ["개통되다"], full: "개통하다/개통되다" },
  { ko: "객차", en: "passenger car" },
  { ko: "화물차", en: "cargo train" },
  { ko: "거동이 불편하다", en: "to have difficulty moving", alt: ["거동이불편하다"] },
  { ko: "거부하다", en: "to refuse" },
  { ko: "거부감", en: "feeling of rejection" },
  { ko: "거주하다", en: "to reside" },
  { ko: "거짓말 탐지기", en: "lie detector", alt: ["거짓말탐지기"] },
  { ko: "건강보험", en: "health insurance" },
  { ko: "건강식", en: "healthfood" },
  { ko: "건강관리", en: "health management" },
  { ko: "건널목", en: "crossing" },
  { ko: "검거하다", en: "to arrest" },
  { ko: "검거 작전", en: "arrest operation", alt: ["검거작전"] },
  { ko: "결과", en: "result" },
  { ko: "결과적으로", en: "as a result" },
  { ko: "결식", en: "going without a meal" },
  { ko: "결식아동 돕기", en: "helping undernourished children", alt: ["결식아동돕기"] },
  { ko: "결핵", en: "tuberculosis(eradication)", full: "결핵(퇴치)" },
  { ko: "겸손하다", en: "to be humble" },
  { ko: "경고하다", en: "to warn" },
  { ko: "경고문", en: "a warning" },
  { ko: "경기회복", en: "economic recovery" },
  { ko: "경기불황", en: "economic recession" },
  { ko: "경기호황", en: "economic boom" },
  { ko: "경상수지", en: "trade balance" },
  { ko: "경위를 조사하다", en: "examine the details", alt: ["경위를조사하다"] },
  { ko: "경향", en: "tendency/trend" },
  { ko: "경험", en: "experience" },
  { ko: "경력", en: "career" },
  { ko: "계모", en: "stepmother" },
  { ko: "계절", en: "season" },
  { ko: "계획하다", en: "to plan" },
  { ko: "계획짜다", en: "to plan" },
  { ko: "계획만들다", en: "to plan" },
  { ko: "고도", en: "altitude/height restriction", alt: ["높이"], full: "고도/높이(제한)" },
  { ko: "고발하다", en: "to report (to the authorities)" },
  { ko: "신고하다", en: "to report (to the authorities)" },
  { ko: "고생스럽다", en: "to be hard to bear, tough" },
  { ko: "고생하다", en: "to experience hardship" },
  { ko: "고소하다", en: "to sue, bring a suit against" },
  { ko: "고아원", en: "orphanage" },
  { ko: "고학력 실업자", en: "highly-educated and unemployed", alt: ["고학력실업자"] },
  { ko: "골수", en: "bone marrow" },
  { ko: "공개하다", en: "to reveal/ to open to the public" },
  { ko: "공고하다", en: "to publicly announce" },
  { ko: "공고문", en: "an announcement" },
  { ko: "공공장소", en: "public place" },
  { ko: "공급하다", en: "to supply" },
  { ko: "공기오염", en: "air pollution" },
  { ko: "대기오염", en: "air pollution" },
  { ko: "공기총", en: "air gun" },
  { ko: "공무원", en: "public servant" },
  { ko: "공직자", en: "public official" },
  { ko: "공휴일", en: "public holiday" },
  { ko: "과반수", en: "more than half/majority" },
  { ko: "과수원", en: "orchard" },
  { ko: "과외", en: "extracurricular private tutoring/teaching" },
  { ko: "과외비", en: "private tutoring fee" },
  { ko: "사교육비", en: "private tutoring fee" },
  { ko: "고액과외", en: "expensive off-campus tutoring" },
  { ko: "관광명소", en: "tourist attraction" },
  { ko: "관광비자", en: "tourist visa" },
  { ko: "관련되다", en: "to be involved with/related" },
  { ko: "관리하다", en: "to manage" },
  { ko: "관리비", en: "management fee" },
  { ko: "관심", en: "interest/concern" },
  { ko: "광우병", en: "mad cow disease" },
  { ko: "괴한", en: "suspicious/unidentified person" },
  { ko: "교권", en: "teacher's authority" },
  { ko: "교육열", en: "enthusiasm for education" },
  { ko: "교통 정체", en: "traffic congestion/standstill", alt: ["교통정체"] },
  { ko: "교통이 마비되다", en: "severe traffic jam", alt: ["교통이마비되다"] },
  { ko: "구르다", en: "to roll over, flip over" },
  { ko: "구속영장을 신청하다", en: "to request an arrest warrant", alt: ["구속영장을신청하다"] },
  { ko: "구입하다", en: "to purchase" },
];

export const DLPT_301_400: BankTerm[] = [
  { ko: "살해하다", en: "murder/murderer", alt: ["살해범", "살인범"], full: "살해하다/살해범/살인범" },
  { ko: "상관이 있다", en: "be correlated to", alt: ["상관이있다"] },
  { ko: "상담하다", en: "consult" },
  { ko: "상류층", en: "upper class" },
  { ko: "상반기", en: "first half of the year/second half of the year", alt: ["하반기"], full: "상반기/하반기" },
  { ko: "상봉하다", en: "reunite" },
  { ko: "상수 도관", en: "water supply pipe/water service/sewage", alt: ["상수도", "하수도 관", "상수도관"], full: "상수 도관/상수도/하수도 관" },
  { ko: "상습", en: "habitual (criminal)", full: "상습 (사범/범)" },
  { ko: "상승하다", en: "rise" },
  { ko: "상태", en: "condition" },
  { ko: "상하다", en: "go bad/spoil" },
  { ko: "생명에 지장이 없다", en: "life not in danger/in danger", alt: ["있다", "생명에지장이없다"], full: "생명에 지장이 없다/있다" },
  { ko: "생사가 확인되지 않다", en: "life or death is not confirmed", alt: ["생사가확인되지않다"] },
  { ko: "생존하다", en: "survive/survivor", alt: ["생존자"], full: "생존하다/생존자" },
  { ko: "서구화", en: "westernization" },
  { ko: "석사", en: "masters degree/doctorate degree", alt: ["박사 학위"], full: "석사/박사 학위" },
  { ko: "선발하다", en: "select" },
  { ko: "선선하다", en: "cool" },
  { ko: "선전하다", en: "advertise", alt: ["광고하다"], full: "선전하다/광고하다" },
  { ko: "선진국", en: "developed/underdeveloped country", alt: ["후진국"], full: "선진국/후진국" },
  { ko: "선택하다", en: "choose/select", alt: ["뽑다", "고르다"], full: "선택하다/뽑다/고르다" },
  { ko: "선호하다", en: "prefer/extent of preference", alt: ["선호도"], full: "선호하다/선호도" },
  { ko: "설사", en: "diarrhea" },
  { ko: "설상가상", en: "to make matters worse" },
  { ko: "설치하다", en: "install" },
  { ko: "섬세하다", en: "delicate/fine/subtle" },
  { ko: "섭취하다", en: "ingest/intake" },
  { ko: "성공하다", en: "successful/succeed" },
  { ko: "성금", en: "donation (money contributed)" },
  { ko: "성능", en: "capacity/performance" },
  { ko: "성수기", en: "peak season" },
  { ko: "성적", en: "grades" },
  { ko: "성추행", en: "rape/sexual assault", alt: ["성폭행"], full: "성추행/성폭행" },
  { ko: "성형 수술", en: "plastic surgery", alt: ["성형수술"] },
  { ko: "성희롱", en: "sexual harassment" },
  { ko: "세면 도구", en: "toiletries", alt: ["세면도구"] },
  { ko: "세무 조사", en: "tax audit", alt: ["세무조사"] },
  { ko: "소동", en: "commotion/agitation" },
  { ko: "소득", en: "income" },
  { ko: "소매치기", en: "pickpocket" },
  { ko: "소문", en: "rumor/word of mouth", alt: ["입 소문"], full: "소문/입 소문" },
  { ko: "소방관", en: "firefighter/fire station/fire engine", alt: ["소방서", "소방차"], full: "소방관/소방서/소방차" },
  { ko: "소비", en: "consumption/spending (consumer/habit)", full: "소비 (자/습관)" },
  { ko: "소설", en: "novel (novelist)", full: "소설 (가)" },
  { ko: "소송을 제기하다", en: "sue/file a lawsuit", alt: ["소송을제기하다"], full: "소송을 제기하다 (걸다/하다)" },
  { ko: "소음 공해", en: "noise pollution", alt: ["소음공해"] },
  { ko: "소탕", en: "clean up of criminals/criminal acts" },
  { ko: "소화", en: "firefighting/extinguishing (operation/fire extinguisher)", full: "소화 (작업/기)" },
  { ko: "소화전", en: "fire hydrant" },
  { ko: "속달", en: "express delivery" },
  { ko: "속이다", en: "to deceive/con" },
  { ko: "손상을 입히다", en: "to damage/be damaged", alt: ["손상을입히다"] },
  { ko: "손짓", en: "hand gesture" },
  { ko: "손해 배상", en: "compensation for damages", alt: ["손해배상"] },
  { ko: "수도", en: "water service (tap/tap water)", full: "수도 (꼭지/수돗물)" },
  { ko: "수류탄", en: "grenade" },
  { ko: "수면", en: "sleep/surface of water" },
  { ko: "수명", en: "life span/life", alt: ["목숨"], full: "수명/목숨" },
  { ko: "수법", en: "method/trick/technique" },
  { ko: "수사하다", en: "investigate", alt: ["조사하다"], full: "수사하다/조사하다" },
  { ko: "수상자", en: "award recipient" },
  { ko: "수색하다", en: "search for/cast a dragnet" },
  { ko: "수송", en: "transportation (cargo plane/unit/air)", full: "수송 (기/대/공중)" },
  { ko: "수업을 받다", en: "take a class/teach", alt: ["하다", "수업을받다"], full: "수업을 받다/하다" },
  { ko: "수요", en: "demand" },
  { ko: "수용하다", en: "accept", alt: ["받아들이다"], full: "수용하다/받아들이다" },
  { ko: "수익", en: "earning/proceeds (earnings/net/gross)", full: "수익 (금/순/총)" },
  { ko: "수임", en: "acceptance of appointment" },
  { ko: "수재민", en: "citizens affected by water disaster" },
  { ko: "수질", en: "water quality (protection/improvement/examination/pollution)", full: "수질 (보호/개선/검사/오염)" },
  { ko: "수혈", en: "blood transfusion" },
  { ko: "숙련공", en: "skilled worker" },
  { ko: "숨지다", en: "die", alt: ["죽다"], full: "숨지다/죽다" },
  { ko: "스스로", en: "of one's own will/voluntarily" },
  { ko: "습도", en: "humidity" },
  { ko: "습진", en: "eczema/moist tetter" },
  { ko: "승소하다", en: "win a lawsuit" },
  { ko: "시각 장애인", en: "blind person/visually impaired", alt: ["시각장애인"] },
  { ko: "시설", en: "facility" },
  { ko: "시위를 벌이다", en: "demonstrate/protest", alt: ["데모하다", "시위를벌이다"], full: "시위를 벌이다/데모하다" },
  { ko: "시청하다", en: "watch (audience/audiovisual)", alt: ["시청자", "시청각"], full: "시청하다/시청자/시청각" },
  { ko: "식구", en: "family members" },
  { ko: "식량", en: "foodstuffs/provisions" },
  { ko: "식목일", en: "Arbor day" },
  { ko: "식물 인간", en: "patient in vegetative state", alt: ["식물인간"] },
  { ko: "식생활", en: "dietary life (sexual/social/group)", full: "식생활 (성/사회/단체)" },
  { ko: "식수", en: "drinking water" },
  { ko: "식중독", en: "food poisoning (alcoholism/workaholic)", full: "식중독 (알코올 중독/일 중독)" },
  { ko: "신경 쓰다", en: "concern oneself about/pay attention to", alt: ["신경쓰다"] },
  { ko: "신경 정신과", en: "department of neuropsychiatry", alt: ["신경정신과"] },
  { ko: "신경통", en: "neuralgia" },
  { ko: "신발", en: "shoes" },
  { ko: "신변", en: "oneself (safety/protection)", full: "신변 (안전/보호)" },
  { ko: "신생", en: "...new born (baby/country/airline company)", full: "신생 (아/국/항공사)" },
  { ko: "신원", en: "one's identity (check/guarantee/proof)", alt: ["신분"], full: "신원/신분 (확인/보증/증명)" },
  { ko: "신장 이식", en: "kidney transplant", alt: ["신장이식"] },
  { ko: "실망하다", en: "be disappointed" },
  { ko: "실수", en: "mistake" },
  { ko: "실시하다", en: "carry out/implement" },
  { ko: "실종되다", en: "be missing" },
];

export const DLPT_401_500: BankTerm[] = [
  { ko: "실험장", en: "experiment site" },
  { ko: "실험하다", en: "to experiment" },
  { ko: "심각하다", en: "be serious/seriousness", alt: ["심각성"], full: "심각하다/심각성" },
  { ko: "심리적", en: "psychological" },
  { ko: "심야 영업", en: "late night business operation", alt: ["심야영업"] },
  { ko: "심장", en: "heart (disease/beat/pacemaker)", full: "심장 (질환/박동/박동기)" },
  { ko: "심판", en: "referee/umpire", full: "심판 (원)" },
  { ko: "쓰러지다", en: "collapse/fall down" },
  { ko: "씨", en: "seed", alt: ["종자"], full: "씨/종자" },
  { ko: "아가방", en: "children's store" },
  { ko: "아랑곳하지 않다", en: "pay no attention to", alt: ["아랑곳하지않다"] },
  { ko: "아쉽다", en: "feel bad" },
  { ko: "악화되다", en: "worsen" },
  { ko: "안락사", en: "euthanasia" },
  { ko: "안심하다", en: "feel assured" },
  { ko: "안전 불감증", en: "insensibility to safety", alt: ["안전불감증"] },
  { ko: "안전 수칙", en: "safety rules", alt: ["안전수칙"] },
  { ko: "안전 조치", en: "safety measures", alt: ["안전조치"] },
  { ko: "안정적", en: "stable" },
  { ko: "암매장", en: "secret burial" },
  { ko: "앞당기다", en: "advance/move up a date" },
  { ko: "애완 동물", en: "pet animal (dog)", alt: ["애완동물"], full: "애완 동물 (견)" },
  { ko: "애용하다", en: "use habitually/patronize/regular user/patron", alt: ["애용가"], full: "애용하다/애용가" },
  { ko: "야간", en: "nighttime" },
  { ko: "양로원", en: "nursing home" },
  { ko: "양모", en: "wool/foster mother" },
  { ko: "어류", en: "fish" },
  { ko: "억제하다", en: "suppress/control plan", alt: ["억제책"], full: "억제하다/억제책" },
  { ko: "언론", en: "media/press" },
  { ko: "업종", en: "type of business/industry" },
  { ko: "여성 단체", en: "women's organization/federation/union", alt: ["연맹", "연합", "여성단체"], full: "여성 단체/연맹/연합" },
  { ko: "여성 인력", en: "female workforce", alt: ["여성인력"] },
  { ko: "역할", en: "role" },
  { ko: "연결하다", en: "connect" },
  { ko: "연기하다", en: "postpone" },
  { ko: "연락이 끊기다", en: "lose touch with someone/be disconnected", alt: ["연락이끊기다"] },
  { ko: "연락처", en: "point of contact" },
  { ko: "연령별", en: "classified by age" },
  { ko: "연령순", en: "order by age" },
  { ko: "연령", en: "age (group/bracket)", full: "연령 (층/대)" },
  { ko: "연맹", en: "league/alliance/federation" },
  { ko: "연설하다", en: "speak to the public" },
  { ko: "연예", en: "entertainment (entertainer/circle)", full: "연예 (인/계)" },
  { ko: "연장", en: "extension (overtime/business/operation/route/line)", full: "연장 (근무/영업/운행/노선/생명)" },
  { ko: "연착하다", en: "arrive late/be delayed", alt: ["연착되다"], full: "연착하다/연착되다" },
  { ko: "연탄", en: "briquette" },
  { ko: "영부인", en: "first lady" },
  { ko: "영아", en: "infant/nursing", alt: ["유아"], full: "영아/유아" },
  { ko: "영향을 주다", en: "influence/affect", alt: ["미치다", "영향을주다"], full: "영향을 주다/미치다" },
  { ko: "예년", en: "ordinary year/average year" },
  { ko: "예방 주사", en: "preventative shot (immunization)", alt: ["예방주사"], full: "예방 주사 (예방 접종)" },
  { ko: "예산", en: "budget (waste/deficit)", full: "예산 (낭비/부족)" },
  { ko: "예술 작품", en: "artwork", alt: ["예술작품"] },
  { ko: "예술성", en: "artistry" },
  { ko: "오락비", en: "entertainment costs" },
  { ko: "오염", en: "pollution (air/water/soil)", full: "오염 (대기/수질/토양)" },
  { ko: "온갖", en: "every/all sorts of" },
  { ko: "온난화", en: "warming (phenomenon)", full: "온난화 (현상)" },
  { ko: "온천", en: "hot spring" },
  { ko: "왕따", en: "ostracize/bully" },
  { ko: "외래 환자", en: "outpatient", alt: ["외래환자"] },
  { ko: "외롭다", en: "be lonely" },
  { ko: "외모", en: "outward appearance" },
  { ko: "외식하다", en: "eat out" },
  { ko: "요구하다", en: "demand" },
  { ko: "요청하다", en: "request" },
  { ko: "용달차", en: "delivery vehicle" },
  { ko: "용돈", en: "spending money/allowance" },
  { ko: "용의자", en: "suspect" },
  { ko: "용품", en: "supplies (childrens/baby/adult)", full: "용품 (아동/유아/성인)" },
  { ko: "우울증", en: "depression" },
  { ko: "운영하다", en: "run/operate" },
  { ko: "운전 면허 취소", en: "revocation of driver's license", alt: ["운전면허취소"] },
  { ko: "운행이 중단되다", en: "suspended operations", alt: ["운행이중단되다"] },
  { ko: "원조 교제", en: "dating in return for money", alt: ["원조교제"] },
  { ko: "원조하다", en: "aid" },
  { ko: "위독하다", en: "be in critical medical condition" },
  { ko: "위반하다", en: "violate" },
  { ko: "위장하다", en: "disguise/camouflage" },
  { ko: "위조하다", en: "counterfeit/forge" },
  { ko: "위치", en: "location" },
  { ko: "위협하다", en: "threaten" },
  { ko: "유족", en: "surviving family", alt: ["유가족"], full: "유족/유가족" },
  { ko: "유괴", en: "abduction/kidnapping" },
  { ko: "유급되다", en: "held back/stay in same class for two years" },
  { ko: "유리하다", en: "advantageous" },
  { ko: "유부녀", en: "married woman/married man", alt: ["유부남"], full: "유부녀/유부남" },
  { ko: "유비 무환", en: "ounce of prevention is better than a pound of cure", alt: ["유비무환"] },
  { ko: "유실", en: "loss (lost item)", full: "유실(물)" },
  { ko: "유아", en: "nursing infant" },
  { ko: "유인하다", en: "lure" },
  { ko: "유일한", en: "the only" },
  { ko: "유적지", en: "historical site" },
  { ko: "유전", en: "heredity (DNA/factor/hereditary)", full: "유전 (자/인자/성)" },
  { ko: "유지하다", en: "maintain" },
  { ko: "유통 기한", en: "period of circulation for perishable food", alt: ["유통기한"] },
  { ko: "유해", en: "harmfulness" },
  { ko: "유행에 앞서 가다", en: "be on leading edge of fashion/follow a trend", alt: ["유행을 따르다", "유행에앞서가다"], full: "유행에 앞서 가다/유행을 따르다" },
  { ko: "유효 기간", en: "valid period/period of circulation of goods", alt: ["유통 기간", "유효기간"], full: "유효 기간/유통 기간" },
  { ko: "유흥 업소", en: "entertainment business", alt: ["유흥업소"] },
];

export const DLPT_501_600: BankTerm[] = [
  { ko: "육안", en: "naked eye" },
  { ko: "융자", en: "financing/loan" },
  { ko: "는데도 불구하고", en: "despite/even though", alt: ["는데도불구하고"] },
  { ko: "은 채", en: "as/being/with/the condition of", alt: ["은채"] },
  { ko: "은퇴하다", en: "retire" },
  { ko: "음란물", en: "pornographic material" },
  { ko: "음성", en: "voice" },
  { ko: "음주", en: "drinking (breathalyzer/DUI)", full: "음주 (검사/운전)" },
  { ko: "응급", en: "emergency (measure/first aid)", full: "응급 (조치/치료)" },
  { ko: "의견", en: "opinion" },
  { ko: "의논하다", en: "discuss" },
  { ko: "의무", en: "duty/obligation/make something mandatory", alt: ["의무화하다"], full: "의무/의무화하다" },
  { ko: "의문이 제기되다", en: "raise a question", alt: ["의문이제기되다"] },
  { ko: "의미 있다", en: "have significance/be meaningful", alt: ["의미있다"] },
  { ko: "의식", en: "consciousness/awareness (survey/structure)", full: "의식 (조사/구조)" },
  { ko: "의식을 잃다", en: "lose consciousness", alt: ["의식을잃다"] },
  { ko: "의심하다", en: "suspect/be suspicious of" },
  { ko: "의약 분업", en: "separation of prescribing and dispensing (doctors vs. pharmacists)", alt: ["의약분업"] },
  { ko: "라고 전하다", en: "report that ~ (quoting)", alt: ["라고전하다"], full: "(이)라고 전하다" },
  { ko: "이력서", en: "resume" },
  { ko: "이륙하다", en: "take off", alt: ["뜨다"], full: "이륙하다/뜨다" },
  { ko: "이산 가족 상봉", en: "reunion of dispersed family members", alt: ["이산가족상봉"] },
  { ko: "이식", en: "transplant (surgery)", full: "이식 (수술)" },
  { ko: "이용원", en: "barbershop", alt: ["이발소", "이발관"], full: "이용원/이발소/이발관" },
  { ko: "이자율", en: "interest rate" },
  { ko: "이전", en: "relocation/moving (office/school/hospital)", full: "이전 (사무실/학교/병원)" },
  { ko: "이탈하다", en: "secede/separate" },
  { ko: "이혼하다", en: "divorce" },
  { ko: "익사", en: "drowning (accident)", full: "익사 (사고)" },
  { ko: "익숙하다", en: "be used to" },
  { ko: "인공호흡", en: "CPR (machine)", full: "인공호흡 (기)" },
  { ko: "인권", en: "human rights (organization/issue)", full: "인권 (단체/문제)" },
  { ko: "인기", en: "popularity (management/draw/maintain)", full: "인기 (관리/를 끌다/를 유지하다)" },
  { ko: "인기 상품", en: "popular product", alt: ["인기상품"] },
  { ko: "인내심", en: "patience" },
  { ko: "인문계", en: "liberal arts" },
  { ko: "인상 착의", en: "physical description/features and clothes", alt: ["인상착의"] },
  { ko: "인생", en: "life" },
  { ko: "인식", en: "recognition" },
  { ko: "인정하다", en: "accept/admit" },
  { ko: "인질극", en: "hostage situation" },
  { ko: "인체", en: "human body" },
  { ko: "인형", en: "doll" },
  { ko: "일거리", en: "job/things to do" },
  { ko: "일부분", en: "part of" },
  { ko: "일부 지역", en: "certain area", alt: ["일부지역"] },
  { ko: "일사병", en: "sunstroke/heatstroke" },
  { ko: "일용직", en: "temporary work" },
  { ko: "일치하다", en: "match/be identical to" },
  { ko: "일회용", en: "disposable/one time use" },
  { ko: "임명하다", en: "appoint" },
  { ko: "임하다", en: "undertake/take on/deal with" },
  { ko: "입국", en: "entering a country" },
  { ko: "입시 경쟁률", en: "entrance exam competition rate", alt: ["입시경쟁률"] },
  { ko: "입양하다", en: "adopt/adopted child", full: "입양하다 (아)" },
  { ko: "입원 환자", en: "inpatient/outpatient", alt: ["외래 환자", "입원환자"], full: "입원 환자/외래 환자" },
  { ko: "입장을 밝히다", en: "state one's position", alt: ["입장을밝히다"] },
  { ko: "입학하다", en: "enter a school/new student/freshman", alt: ["입학생"], full: "입학하다/입학생" },
  { ko: "잇따라", en: "consecutively" },
  { ko: "자격", en: "qualification (license/certification)", full: "자격 (증)" },
  { ko: "자동 응답기", en: "answering machine", alt: ["자동응답기"] },
  { ko: "자동 번역기", en: "translation machine (automatic)", alt: ["자동번역기"], full: "자동 번역기 (계)" },
  { ko: "자리를 잡다", en: "settle down", alt: ["자리를잡다"] },
  { ko: "자백하다", en: "confess" },
  { ko: "자세히", en: "in detail", alt: ["상세히"], full: "자세히/상세히" },
  { ko: "자신", en: "oneself" },
  { ko: "자연 보존", en: "preserve/protect the environment", alt: ["자연을 지키다", "자연보존"], full: "자연 보존 (보호)/자연을 지키다" },
  { ko: "자원하다", en: "volunteer (work)", full: "자원하다 (봉사)" },
  { ko: "작가", en: "writer" },
  { ko: "잔돈", en: "change/small money" },
  { ko: "잔인하다", en: "be cruel" },
  { ko: "장기 기증", en: "organ donation/transplant", alt: ["이식", "장기기증"], full: "장기 기증/이식" },
  { ko: "장기 매매", en: "organ sales", alt: ["장기매매"] },
  { ko: "장기수", en: "long term prisoner (POW)", full: "장기수 (포로)" },
  { ko: "장난감", en: "toy" },
  { ko: "장난하다", en: "play/joke around/be mischievous" },
  { ko: "장남", en: "oldest son" },
  { ko: "장병", en: "officers and men/servicemen" },
  { ko: "장점", en: "strong point/weak point", alt: ["단점"], full: "장점/단점" },
  { ko: "장학금", en: "scholarship" },
  { ko: "재고", en: "reconsideration/inventory" },
  { ko: "재배하다", en: "grow (a plant)" },
  { ko: "재산 피해", en: "property damage", alt: ["재산피해"] },
  { ko: "재생", en: "recycling (items)", full: "재생 (품)" },
  { ko: "재외 국민", en: "citizens abroad", alt: ["재외국민"] },
  { ko: "재판장", en: "chief judge" },
  { ko: "재학생", en: "currently enrolled students" },
  { ko: "재혼", en: "remarriage" },
  { ko: "저렴하다", en: "cheap/cheap price", alt: ["저렴한 가격"], full: "저렴하다/저렴한 가격" },
  { ko: "저소득", en: "low income" },
  { ko: "저자", en: "author" },
  { ko: "저축", en: "saving money" },
  { ko: "적당하다", en: "suitable (amount)", full: "적당하다 (량)" },
  { ko: "적설", en: "snowfall (amount)", full: "적설 (량)" },
  { ko: "적용하다", en: "apply (a method/policy)" },
  { ko: "전과자", en: "one with a criminal history" },
  { ko: "전관 예우", en: "courtesy treatment of predecessor", alt: ["전관예우"] },
  { ko: "전달하다", en: "deliver/convey (intention/letter)", full: "전달하다 (뜻을/편지를)" },
  { ko: "전담반", en: "taskforce/squad (adolescent/drug)", full: "전담반 (청소년/마약)" },
  { ko: "전망되다", en: "be forecast/anticipated (anticipate)", alt: ["하다"], full: "전망되다/하다" },
];

export const DLPT_601_700: BankTerm[] = [
  { ko: "전면 해제", en: "total cancellation/withdrawal (entire withdrawal of martial law)", alt: ["전면해제"], full: "전면 해제 (비상 계엄령)" },
  { ko: "전문가", en: "expert", full: "전문가 (인)" },
  { ko: "전복되다", en: "be overturned", full: "전복되다 (뒤집히다)" },
  { ko: "전시", en: "exhibition", full: "전시 (회)" },
  { ko: "전염병", en: "contagious disease/epidemic" },
  { ko: "전용", en: "exclusive use" },
  { ko: "전용", en: "exclusive use (airplane/bus/handicapped only)", full: "전용 (기 버스/장애인)" },
  { ko: "전자파", en: "electromagnetic wave" },
  { ko: "전화위복", en: "turn a misfortune into a blessing" },
  { ko: "절도", en: "theft/larceny" },
  { ko: "절약하다", en: "to be frugal" },
  { ko: "점검하다", en: "to check" },
  { ko: "접근하다", en: "to approach" },
  { ko: "접대", en: "reception/entertainment for a guest" },
  { ko: "접촉 사고", en: "minor collision/fender bender", alt: ["접촉사고"] },
  { ko: "정기 휴일", en: "regular day off", alt: ["정기휴일"] },
  { ko: "정년 퇴직", en: "retirement at age limit", alt: ["정년퇴직"] },
  { ko: "정맥", en: "vein" },
  { ko: "정면 충돌", en: "head on collision", alt: ["정면충돌"] },
  { ko: "정보 수집 능력", en: "intelligence collection ability", alt: ["정보수집능력"] },
  { ko: "정복하다", en: "to conquer" },
  { ko: "정성", en: "sincerity/earnestness" },
  { ko: "정신 건강", en: "mental health", alt: ["정신건강"] },
  { ko: "정신과 의사", en: "psychiatrist", alt: ["정신과의사"] },
  { ko: "정신 질환", en: "mental illness (insane/mentally retarded child)", alt: ["정신질환"], full: "정신 질환 (정신 이상자/정신 지체아)" },
  { ko: "정장", en: "formal wear/full dress" },
  { ko: "정차하다", en: "to stop a vehicle" },
  { ko: "젖을 먹이다", en: "to breastfeed", alt: ["젖을먹이다"] },
  { ko: "제거하다", en: "to remove/eliminate" },
  { ko: "제공하다", en: "to provide" },
  { ko: "제안하다", en: "to propose" },
  { ko: "제외하다", en: "to exclude" },
  { ko: "제작하다", en: "to produce" },
  { ko: "제출하다", en: "to submit" },
  { ko: "제한하다", en: "to limit", alt: ["한정하다"], full: "제한하다/한정하다" },
  { ko: "조기 발견", en: "early discovery/detection", alt: ["조기발견"] },
  { ko: "조기 유학", en: "early age study abroad", alt: ["조기유학"] },
  { ko: "조명탄", en: "flare (illumination round)" },
  { ko: "조사 결과", en: "investigation result", alt: ["조사결과"] },
  { ko: "조약", en: "treaty" },
  { ko: "조약을 맺다", en: "conclude/enter into a treaty", alt: ["조약을맺다"] },
  { ko: "조직 검사", en: "biopsy", alt: ["조직검사"] },
  { ko: "조치", en: "take measures/arrange", alt: ["조처하다"], full: "조치/조처하다" },
  { ko: "종류", en: "type/kind/sort" },
  { ko: "주간", en: "weekly/daytime" },
  { ko: "주름", en: "wrinkle (to be creased)", full: "주름 (이 잡히다)" },
  { ko: "주머니가 가볍다", en: "light pockets/have no money", alt: ["주머니가가볍다"] },
  { ko: "주문하다", en: "to order" },
  { ko: "주부", en: "housewife" },
  { ko: "주시하다", en: "to observe closely/pay close attention to" },
  { ko: "주식", en: "stocks/investment in stocks", alt: ["투자"], full: "주식/투자" },
  { ko: "주의를 기울이다", en: "pay attention", alt: ["주의를기울이다"] },
  { ko: "주의를 주다", en: "give a warning", alt: ["주의를주다"] },
  { ko: "준수하다", en: "to obey (the law)", full: "준수하다 (법을)" },
  { ko: "줄", en: "cord/electric cord/spider web", full: "줄 (전깃줄/거미줄)" },
  { ko: "줄", en: "stripes (striped pattern)", full: "줄 (무늬)" },
  { ko: "줄이다", en: "to reduce" },
  { ko: "중고", en: "used (car/item)", full: "중고 (차/품)" },
  { ko: "중단", en: "discontinue/suspend" },
  { ko: "중독 증세", en: "addiction/poisoning symptoms", alt: ["중독증세"] },
  { ko: "중산층", en: "middle class", alt: ["중류층"], full: "중산층/중류층" },
  { ko: "중상", en: "heavy injury/slander" },
  { ko: "중태", en: "serious condition" },
  { ko: "중풍", en: "stroke/paralysis" },
  { ko: "중형", en: "medium size/heavy penalty" },
  { ko: "중화상", en: "severe burn injury" },
  { ko: "증가하다", en: "to increase" },
  { ko: "증권", en: "certificate of stock/shares" },
  { ko: "증세를 보이다", en: "show symptoms", alt: ["증세를보이다"] },
  { ko: "증편하다", en: "to increase (number of flights)" },
  { ko: "지갑", en: "wallet" },
  { ko: "지뢰", en: "landmine" },
  { ko: "지문", en: "fingerprint" },
  { ko: "지속되다", en: "to continue" },
  { ko: "지역 차별", en: "regional discrimination", alt: ["지역차별"] },
  { ko: "지연되다", en: "be delayed" },
  { ko: "지원하다", en: "apply (application/applicant/eligibility)", full: "지원하다 (서/자/자격)" },
  { ko: "지적하다", en: "to point out" },
  { ko: "지지하다", en: "to support" },
  { ko: "직장", en: "workplace (worker)", full: "직장 (인)" },
  { ko: "직접", en: "directly" },
  { ko: "진단을 받다", en: "receive diagnosis (to diagnose)", alt: ["진단을받다"], full: "진단을 받다 (하다)" },
  { ko: "진동을 느끼다", en: "feel vibration", alt: ["진동을느끼다"] },
  { ko: "진료", en: "diagnosis (examination + treatment)", full: "진료 (진찰 + 치료)" },
  { ko: "진술", en: "statement" },
  { ko: "진화 작업", en: "firefighting operation", alt: ["진화작업"] },
  { ko: "질식하다", en: "to suffocate" },
  { ko: "집단 괴롭힘", en: "group/mass ostracizing", alt: ["집단괴롭힘"] },
  { ko: "집단 식중독", en: "mass food poisoning", alt: ["집단식중독"] },
  { ko: "집단 구타", en: "group assault", alt: ["폭행", "집단구타"], full: "집단 구타/폭행" },
  { ko: "집배원", en: "postman/postal delivery personnel" },
  { ko: "집중하다", en: "concentrate (heavy deployment/localized torrential rain)", full: "집중하다 (배치/호우)" },
  { ko: "징역형", en: "prison sentence" },
  { ko: "찌르다", en: "stab/be stabbed", alt: ["찔리다"], full: "찌르다/찔리다" },
  { ko: "차를 뽑다", en: "buy a new car", alt: ["차를뽑다"] },
  { ko: "차별", en: "discrimination (gender/age/education)", full: "차별 (남녀/연령/학력)" },
  { ko: "차이", en: "difference (have/have no)", full: "차이 (있다/없다)" },
  { ko: "참가하다", en: "participate (participant/eligibility)", full: "참가하다 (차/자격)" },
  { ko: "참사", en: "disaster/disastrous accident" },
  { ko: "참석하다", en: "to attend" },
];

export const DLPT_701_800: BankTerm[] = [
  { ko: "참여하다", en: "participate" },
  { ko: "참을성", en: "patience", alt: ["인내심"], full: "참을성/인내심" },
  { ko: "채식", en: "vegetarian diet" },
  { ko: "채용하다", en: "to hire" },
  { ko: "책임감", en: "sense of responsibility" },
  { ko: "처녀", en: "virgin (unmarried man)", full: "처녀 (총각)" },
  { ko: "처방", en: "prescription" },
  { ko: "천고마비", en: "plentiful autumn" },
  { ko: "천장", en: "ceiling" },
  { ko: "청각 장애자", en: "hearing impaired person", alt: ["청각장애자"] },
  { ko: "청년", en: "youth/young man" },
  { ko: "체벌하다", en: "inflict disciplinary physical punishment" },
  { ko: "체중", en: "weight (body weight)", full: "체중 (몸무게)" },
  { ko: "체험", en: "to experience", alt: ["경험하다"], full: "체험/경험하다" },
  { ko: "체형", en: "body type" },
  { ko: "초보자", en: "beginner" },
  { ko: "초청장", en: "invitation card" },
  { ko: "촉구하다", en: "to urge" },
  { ko: "총상", en: "gunshot wound" },
  { ko: "총장", en: "university president" },
  { ko: "총학생회", en: "general student association" },
  { ko: "최면", en: "hypnosis" },
  { ko: "최신예기", en: "state of the art aircraft" },
  { ko: "최첨단", en: "state of the art" },
  { ko: "추격하다", en: "to chase" },
  { ko: "추적하다", en: "to track" },
  { ko: "추진하다", en: "to promote/drive forward" },
  { ko: "추천하다", en: "to recommend" },
  { ko: "축전", en: "festival", alt: ["축제"], full: "축전/축제" },
  { ko: "출국", en: "leaving a country" },
  { ko: "출근", en: "going to work" },
  { ko: "출동하다", en: "to go out/take action" },
  { ko: "출마", en: "running for office" },
  { ko: "출산하다", en: "to give birth", alt: ["아이를 낳다"], full: "출산하다/아이를 낳다" },
  { ko: "충동적", en: "impulsive" },
  { ko: "충분하다", en: "to be enough/sufficient" },
  { ko: "취소하다", en: "to cancel" },
  { ko: "취업", en: "employment (rate/difficulty)", full: "취업 (률/난)" },
  { ko: "치료제", en: "medicine/medical treatment material" },
  { ko: "치료하다", en: "treat/be treated", alt: ["치료받다"], full: "치료하다/치료받다" },
  { ko: "치매", en: "dementia" },
  { ko: "치아", en: "teeth" },
  { ko: "친목회", en: "social gathering" },
  { ko: "침몰하다", en: "to sink" },
  { ko: "침수되다", en: "to be submerged" },
  { ko: "침투하다", en: "to infiltrate" },
  { ko: "침해받다", en: "be violated" },
  { ko: "타계하다", en: "to pass away" },
  { ko: "탁아소", en: "daycare center" },
  { ko: "탄두", en: "warhead" },
  { ko: "탈모", en: "hair loss" },
  { ko: "탈북자", en: "defector" },
  { ko: "탈선", en: "derailment" },
  { ko: "탈옥", en: "prison escape" },
  { ko: "탈출하다", en: "to escape" },
  { ko: "탑승하다", en: "to board a vessel/passenger", alt: ["탑승자"], full: "탑승하다/탑승자" },
  { ko: "털리다", en: "be robbed" },
  { ko: "통과하다", en: "to pass through" },
  { ko: "통제하다", en: "to control" },
  { ko: "통증", en: "pain" },
  { ko: "퇴근 후", en: "after work", alt: ["퇴근후"] },
  { ko: "퇴임", en: "retire/retire by age limit", alt: ["퇴직하다", "정년"], full: "퇴임/퇴직하다/정년" },
  { ko: "투약하다", en: "to administer medicine/medicate" },
  { ko: "투입하다", en: "to put/throw in" },
  { ko: "투자하다", en: "to invest" },
  { ko: "투표하다", en: "to vote" },
  { ko: "특별 단속", en: "special crackdown", alt: ["특별단속"] },
  { ko: "특성", en: "special characteristics" },
  { ko: "특이하다", en: "unique" },
  { ko: "파괴하다", en: "to destroy/be destroyed", alt: ["되다"], full: "파괴하다/되다" },
  { ko: "파업하다", en: "to go on strike" },
  { ko: "파출소", en: "police substation (chief)", full: "파출소 (장)" },
  { ko: "판결", en: "judicial decision/ruling" },
  { ko: "판명되다", en: "to prove to be/turn out to be" },
  { ko: "판사", en: "judge" },
  { ko: "편의", en: "convenience (facility)", full: "편의 (시설)" },
  { ko: "평등", en: "equality (gender/employment)", full: "평등 (남녀/고용)" },
  { ko: "평론가", en: "critic/commentator" },
  { ko: "평생교육", en: "lifelong education" },
  { ko: "폐기물", en: "waste matter" },
  { ko: "폐쇄 회로 화면", en: "closed circuit screen", alt: ["폐쇄회로화면"] },
  { ko: "폐쇄하다", en: "to close" },
  { ko: "폐암", en: "lung cancer" },
  { ko: "폐업", en: "discontinuance of business" },
  { ko: "포기하다", en: "to give up" },
  { ko: "포도주", en: "wine" },
  { ko: "포함하다", en: "to include" },
  { ko: "폭동", en: "riot" },
  { ko: "폭로하다", en: "to disclose/reveal (secret/to media)", full: "폭로하다 (비밀을/언론에)" },
  { ko: "폭음", en: "heavy drinking" },
  { ko: "폭주족", en: "motorcycle gang" },
  { ko: "폭포", en: "waterfall" },
  { ko: "피부", en: "skin (cancer)", full: "피부 (암)" },
  { ko: "피서", en: "escape the heat (summer season/visitor)", full: "피서 (철/객)" },
  { ko: "피해를 입다", en: "be damaged/suffer damage", alt: ["주다", "피해를입다"], full: "피해를 입다/주다" },
  { ko: "피해자", en: "victim" },
  { ko: "하락하다", en: "to drop/decrease" },
  { ko: "하산하다", en: "to descend a mountain" },
  { ko: "하숙집", en: "boarding house" },
  { ko: "하행선", en: "downward bound line/away from Seoul" },
];
