import type { Article, Clip } from "./types";

/**
 * Second batch of DLPT-style stories and clips, written to recycle the
 * vocabulary from the learner's Quizlet DLPT sets (see dlptBank.ts) in
 * news context. Original texts written for learners.
 */
export const DLPT_ARTICLES_2: Article[] = [
  {
    id: "dlpt-earthquake",
    kind: "news",
    track: "dlpt",
    title: "남부 지역 강진, 긴급 구조 활동",
    titleEn: "Strong earthquake in the south; emergency rescue under way",
    topic: "World",
    level: "B1",
    date: "2026-10-04",
    emoji: "🏚️",
    sentences: [
      { ko: "어젯밤 남부 지역에서 큰 강진이 발생했습니다.", en: "A powerful earthquake struck the southern region last night." },
      { ko: "지진으로 오래된 건물 여러 채가 붕괴되었고 도로 곳곳이 갈라졌습니다.", en: "Several old buildings collapsed and roads cracked in many places." },
      { ko: "소방 당국은 구조대를 투입해 긴급 구조 활동을 벌이고 있습니다.", en: "Fire authorities have deployed rescue teams and are carrying out emergency rescue operations." },
      { ko: "지금까지 열두 명이 구조되었고 실종자 수색이 계속되고 있습니다.", en: "Twelve people have been rescued so far, and the search for the missing continues." },
      { ko: "목격자들은 건물이 순식간에 무너졌다고 말했습니다.", en: "Witnesses said the building collapsed in an instant." },
      { ko: "정부는 피해 지역 주민들에게 학교와 체육관으로 대피하라고 당부했습니다.", en: "The government urged residents of affected areas to evacuate to schools and gyms." },
    ],
  },
  {
    id: "dlpt-subway-line",
    kind: "news",
    track: "dlpt",
    title: "새 지하철 노선 개통",
    titleEn: "New subway line opens",
    topic: "Society",
    level: "A2",
    date: "2026-09-29",
    emoji: "🚆",
    sentences: [
      { ko: "수도권에 새로운 지하철 노선이 오늘 개통되었습니다.", en: "A new subway line opened in the capital area today." },
      { ko: "이 노선은 도심과 신도시를 삼십 분 안에 연결합니다.", en: "The line connects downtown and the new town in under thirty minutes." },
      { ko: "출근 시간마다 교통 정체를 겪던 시민들은 크게 반겼습니다.", en: "Citizens who suffered traffic congestion every rush hour warmly welcomed it." },
      { ko: "첫날부터 객차 안은 승객으로 붐볐습니다.", en: "From the first day, the cars were crowded with passengers." },
      { ko: "다른 노선으로 갈아타는 역도 다섯 곳이나 됩니다.", en: "There are as many as five stations for transferring to other lines." },
      { ko: "시는 공휴일에도 열차를 평소처럼 운행할 계획입니다.", en: "The city plans to run trains as usual on public holidays too." },
    ],
  },
  {
    id: "dlpt-recession",
    kind: "news",
    track: "dlpt",
    title: "경기 불황에 고학력 실업자 늘어",
    titleEn: "Recession swells the ranks of educated jobless",
    topic: "Economy",
    level: "B1",
    date: "2026-09-24",
    emoji: "📉",
    sentences: [
      { ko: "경기 불황이 길어지면서 고학력 실업자가 늘고 있습니다.", en: "As the recession drags on, the number of highly educated unemployed is growing." },
      { ko: "대학원을 졸업하고도 일자리를 찾지 못하는 청년이 많습니다.", en: "Many young people can't find jobs even after finishing graduate school." },
      { ko: "물가 상승으로 생활비 부담이 커지자 맞벌이 부부도 증가했습니다.", en: "As rising prices increased the cost of living, dual-income couples also increased." },
      { ko: "일부 기업은 비용을 줄이기 위해 명예퇴직을 실시하고 있습니다.", en: "Some companies are offering voluntary early retirement to cut costs." },
      { ko: "전문가들은 경기 회복에는 시간이 더 걸릴 것으로 내다봤습니다.", en: "Experts predicted economic recovery will take more time." },
    ],
  },
  {
    id: "dlpt-smuggling",
    kind: "news",
    track: "dlpt",
    title: "마약 밀수 조직 검거",
    titleEn: "Drug-smuggling ring arrested",
    topic: "Security",
    level: "B2",
    date: "2026-09-20",
    emoji: "🚔",
    sentences: [
      { ko: "경찰이 해외에서 마약을 몰래 들여온 밀수 조직을 검거했습니다.", en: "Police arrested a smuggling ring that secretly brought in drugs from overseas." },
      { ko: "이들은 마약을 화물 속에 숨겨 공항과 항구를 통해 들여온 것으로 드러났습니다.", en: "It emerged that they hid the drugs in cargo and brought them in through airports and ports." },
      { ko: "경찰은 석 달 동안의 검거 작전 끝에 조직원 열다섯 명을 붙잡았습니다.", en: "After a three-month arrest operation, police caught fifteen members of the ring." },
      { ko: "이 가운데 불법 체류자 세 명도 포함되어 있었습니다.", en: "Among them were three illegal immigrants." },
      { ko: "경찰은 주범 두 명에 대해 구속영장을 신청했습니다.", en: "Police requested arrest warrants for the two ringleaders." },
    ],
  },
  {
    id: "dlpt-hit-and-run",
    kind: "news",
    track: "dlpt",
    title: "빙판길 뺑소니 운전자 검거",
    titleEn: "Hit-and-run driver on icy road caught",
    topic: "Society",
    level: "B1",
    date: "2026-09-16",
    emoji: "🚨",
    sentences: [
      { ko: "어젯밤 빙판길에서 차량이 미끄러지면서 건널목을 건너던 노인을 쳤습니다.", en: "Last night a car skidded on an icy road and hit an elderly person crossing at a crosswalk." },
      { ko: "운전자는 사고 직후 그대로 달아났습니다.", en: "The driver fled immediately after the accident." },
      { ko: "사고를 목격한 시민이 바로 경찰에 신고했습니다.", en: "A citizen who witnessed the accident reported it to police right away." },
      { ko: "경찰은 주변 블랙박스 영상을 분석해 뺑소니 운전자를 검거했습니다.", en: "Police analyzed nearby dashcam footage and arrested the hit-and-run driver." },
      { ko: "피해자는 병원으로 옮겨져 치료를 받고 있습니다.", en: "The victim was taken to hospital and is receiving treatment." },
    ],
  },
  {
    id: "dlpt-dmz",
    kind: "news",
    track: "dlpt",
    title: "북한군, 군사분계선 침범 후 복귀",
    titleEn: "North Korean troops cross the MDL, then pull back",
    topic: "Security",
    level: "B2",
    date: "2026-09-12",
    emoji: "⚠️",
    sentences: [
      { ko: "북한군 병력 일부가 오늘 새벽 군사분계선을 넘었다가 돌아갔습니다.", en: "Some North Korean troops crossed the Military Demarcation Line early this morning and then went back." },
      { ko: "우리 군은 경고 방송과 경고 사격을 실시했습니다.", en: "Our military issued warning broadcasts and fired warning shots." },
      { ko: "군 당국은 이번 행동을 의도적인 도발로 보고 경계 태세를 강화했습니다.", en: "Military authorities regard it as a deliberate provocation and raised their alert posture." },
      { ko: "접경 지역에서는 예정대로 민방위 훈련이 진행되었습니다.", en: "Civil defense drills went ahead as scheduled in border areas." },
      { ko: "정부는 북한에 재발 방지를 강력히 요구했습니다.", en: "The government strongly demanded that North Korea prevent a recurrence." },
    ],
  },
  {
    id: "dlpt-private-education",
    kind: "news",
    track: "dlpt",
    title: "사교육비 역대 최고",
    titleEn: "Private education spending hits a record",
    topic: "Society",
    level: "B1",
    date: "2026-09-08",
    emoji: "📚",
    sentences: [
      { ko: "지난해 초중고 학생의 사교육비가 역대 최고를 기록했습니다.", en: "Private education spending for K–12 students hit a record high last year." },
      { ko: "높은 교육열 때문에 많은 부모가 자녀를 학원과 과외에 보냅니다.", en: "Because of the strong passion for education, many parents send their children to cram schools and private tutoring." },
      { ko: "일부 지역에서는 한 달에 수백만 원이 드는 고액 과외도 성행하고 있습니다.", en: "In some areas, expensive tutoring costing several million won a month is widespread." },
      { ko: "교사들은 사교육이 늘면서 교권이 약해지고 있다고 걱정합니다.", en: "Teachers worry that their authority is weakening as private education grows." },
      { ko: "정부는 공교육을 강화해 사교육비 부담을 줄이겠다고 밝혔습니다.", en: "The government said it will strengthen public education to reduce the burden of private tutoring costs." },
    ],
  },
  {
    id: "dlpt-diabetes",
    kind: "news",
    track: "dlpt",
    title: "당뇨병 환자 오백만 명 넘어",
    titleEn: "Diabetes patients top five million",
    topic: "Society",
    level: "B1",
    date: "2026-09-02",
    emoji: "🩺",
    sentences: [
      { ko: "국내 당뇨병 환자가 처음으로 오백만 명을 넘었습니다.", en: "The number of diabetes patients in Korea topped five million for the first time." },
      { ko: "특히 비만아가 늘면서 어린이 당뇨병 환자도 증가하고 있습니다.", en: "With more obese children, cases of childhood diabetes are also rising." },
      { ko: "전문가들은 운동 부족과 기름진 음식을 주요 원인으로 꼽았습니다.", en: "Experts cited lack of exercise and greasy food as the main causes." },
      { ko: "당뇨병 약을 복용하는 환자는 부작용이 없는지 정기적으로 검사를 받아야 합니다.", en: "Patients taking diabetes medication should get regular checkups for side effects." },
      { ko: "건강보험공단은 무료 건강 검진 대상을 확대하기로 했습니다.", en: "The National Health Insurance Service decided to expand eligibility for free health screenings." },
    ],
  },
  {
    id: "dlpt-charity",
    kind: "news",
    track: "dlpt",
    title: "연말 불우 이웃 돕기 모금 시작",
    titleEn: "Year-end fundraising for neighbors in need begins",
    topic: "Society",
    level: "A2",
    date: "2026-08-27",
    emoji: "🤲",
    sentences: [
      { ko: "연말을 맞아 불우 이웃을 돕기 위한 모금 운동이 시작되었습니다.", en: "A fundraising campaign to help neighbors in need has begun for the year end." },
      { ko: "모금된 돈은 결식아동과 홀몸 노인, 노숙자를 지원하는 데 쓰입니다.", en: "The money raised will support undernourished children, seniors living alone and homeless people." },
      { ko: "많은 자원봉사자가 고아원과 복지 시설을 찾아 봉사 활동을 했습니다.", en: "Many volunteers visited orphanages and welfare facilities to do volunteer work." },
      { ko: "한 기업은 직원들의 월급 일부를 모아 기부했습니다.", en: "One company pooled part of its employees' salaries and donated it." },
      { ko: "주최 측은 작은 정성이 큰 힘이 된다며 참여를 부탁했습니다.", en: "Organizers asked people to join, saying small kindnesses add up to great strength." },
    ],
  },
  {
    id: "dlpt-arson",
    kind: "news",
    track: "dlpt",
    title: "대낮 귀금속 상점 화재, 방화 의심",
    titleEn: "Daytime fire at a jewelry store; arson suspected",
    topic: "Security",
    level: "B1",
    date: "2026-08-21",
    emoji: "🔥",
    sentences: [
      { ko: "대낮에 한 귀금속 상점에서 불이 나 경찰이 수사에 나섰습니다.", en: "A fire broke out at a jewelry store in broad daylight, and police have opened an investigation." },
      { ko: "경찰은 괴한이 귀금속을 훔친 뒤 증거를 없애려고 불을 지른 것으로 보고 있습니다.", en: "Police believe an unidentified man stole jewelry and then set the fire to destroy evidence." },
      { ko: "가게 주인은 화재 직전에 수상한 남자가 가게 주변을 배회했다고 진술했습니다.", en: "The shop owner stated that a suspicious man had been loitering around the store just before the fire." },
      { ko: "다행히 화재는 곧 진압되었고 인명 피해는 없었습니다.", en: "Fortunately the fire was soon put out and no one was hurt." },
      { ko: "경찰은 방화와 도난 사건으로 보고 용의자를 추적하고 있습니다.", en: "Police are treating it as arson and theft and are tracking the suspect." },
    ],
  },
  {
    id: "dlpt-autumn-tourism",
    kind: "news",
    track: "dlpt",
    title: "단풍철 관광명소에 인파",
    titleEn: "Crowds flock to tourist spots in foliage season",
    topic: "Culture",
    level: "A2",
    date: "2026-10-02",
    emoji: "🍁",
    sentences: [
      { ko: "단풍이 절정을 이루면서 전국의 관광명소에 사람들이 몰리고 있습니다.", en: "With the autumn foliage at its peak, people are flocking to tourist attractions nationwide." },
      { ko: "설악산에는 지난 주말에만 십만 명이 넘는 등산객이 찾았습니다.", en: "More than 100,000 hikers visited Seoraksan last weekend alone." },
      { ko: "성수기를 맞아 숙박 요금도 크게 올랐습니다.", en: "With the peak season, lodging prices have also risen sharply." },
      { ko: "관광비자 절차가 간소화되면서 외국인 관광객도 늘었습니다.", en: "Foreign tourists have also increased as tourist-visa procedures were simplified." },
      { ko: "주말 농장과 과수원에서 사과 따기 체험을 하는 가족도 많습니다.", en: "Many families are also picking apples at weekend farms and orchards." },
    ],
  },
  {
    id: "dlpt-air-pollution",
    kind: "news",
    track: "dlpt",
    title: "수도권 미세먼지 경보",
    titleEn: "Fine-dust alert issued for the capital area",
    topic: "World",
    level: "B1",
    date: "2026-08-15",
    emoji: "😷",
    sentences: [
      { ko: "오늘 수도권에 미세먼지 경보가 내려졌습니다.", en: "A fine-dust alert was issued for the capital area today." },
      { ko: "대기오염이 심해지자 정부는 노약자에게 외출을 자제하라고 경고했습니다.", en: "As air pollution worsened, the government warned the elderly and frail to avoid going out." },
      { ko: "공공장소와 학교에서는 야외 활동이 제한되었습니다.", en: "Outdoor activities were restricted at public places and schools." },
      { ko: "전문가들은 외출할 때 마스크를 꼭 착용하라고 조언했습니다.", en: "Experts advised wearing a mask whenever going out." },
      { ko: "정부는 차량 운행 제한과 같은 긴급 대책을 시행하고 있습니다.", en: "The government is enforcing emergency measures such as restrictions on driving." },
    ],
  },
  {
    id: "dlpt-bribery",
    kind: "news",
    track: "dlpt",
    title: "공무원 뇌물 비리 적발",
    titleEn: "Civil servants caught in bribery scandal",
    topic: "Politics",
    level: "B2",
    date: "2026-08-09",
    emoji: "💼",
    sentences: [
      { ko: "건설 사업을 맡은 공무원들이 업체로부터 뇌물을 받은 혐의로 체포되었습니다.", en: "Civil servants in charge of a construction project were arrested on charges of taking bribes from a contractor." },
      { ko: "검찰에 따르면 이들은 공사를 맡기는 대가로 수억 원을 받았습니다.", en: "According to prosecutors, they received hundreds of millions of won in exchange for awarding the work." },
      { ko: "이번 비리는 내부 직원의 고발로 처음 알려졌습니다.", en: "The corruption first came to light through a whistleblower inside the office." },
      { ko: "한 공무원은 자신이 누명을 썼다고 주장하고 있습니다.", en: "One official claims he has been falsely accused." },
      { ko: "정부는 공직자의 부정행위를 강력히 단속하겠다고 밝혔습니다.", en: "The government said it will crack down hard on misconduct by public officials." },
    ],
  },
  {
    id: "dlpt-flood",
    kind: "news",
    track: "dlpt",
    title: "집중호우로 내륙 마을 침수",
    titleEn: "Torrential rain floods inland villages",
    topic: "World",
    level: "A2",
    date: "2026-07-30",
    emoji: "🌧️",
    sentences: [
      { ko: "사흘 동안 계속된 집중호우로 내륙 지방의 마을이 물에 잠겼습니다.", en: "Three days of torrential rain left inland villages under water." },
      { ko: "차량 수십 대가 떠내려가고 농경지도 큰 피해를 입었습니다.", en: "Dozens of vehicles were swept away and farmland was badly damaged." },
      { ko: "주민 오백 명이 인근 학교로 대피했습니다.", en: "Five hundred residents evacuated to a nearby school." },
      { ko: "지방자치단체는 비축 식량과 생필품을 긴급히 공급했습니다.", en: "The local government urgently supplied stockpiled food and daily necessities." },
      { ko: "정부는 수해 대책을 마련하고 피해 복구를 지원할 계획입니다.", en: "The government plans to prepare flood countermeasures and support recovery." },
    ],
  },
];

export const DLPT_CLIPS_2: Clip[] = [
  {
    id: "clip-lost-wallet",
    kind: "clip",
    track: "opi",
    title: "분실물 신고",
    titleEn: "Reporting a lost wallet",
    topic: "Life",
    level: "A2",
    emoji: "👛",
    sentences: [
      { ko: "지갑을 잃어버려서 분실 신고를 하러 왔어요.", en: "I lost my wallet, so I came to report it.", speaker: "B" },
      { ko: "언제 어디에서 잃어버리셨어요?", en: "When and where did you lose it?", speaker: "A" },
      { ko: "어제 저녁에 지하철에서 내린 뒤에 없어졌어요.", en: "It disappeared after I got off the subway last night.", speaker: "B" },
      { ko: "지갑 안에 무엇이 들어 있었나요?", en: "What was in the wallet?", speaker: "A" },
      { ko: "신분증과 카드, 현금이 조금 있었어요.", en: "My ID, cards and a little cash.", speaker: "B" },
      { ko: "찾으면 바로 연락드리겠습니다.", en: "We'll contact you as soon as we find it.", speaker: "A" },
    ],
  },
  {
    id: "clip-clinic",
    kind: "clip",
    track: "opi",
    title: "병원에서 증상 말하기",
    titleEn: "Describing symptoms at a clinic",
    topic: "Life",
    level: "A2",
    emoji: "💊",
    sentences: [
      { ko: "어디가 불편하세요?", en: "What seems to be the problem?", speaker: "A" },
      { ko: "어제부터 두통이 심하고 복통도 있어요.", en: "I've had a bad headache since yesterday, and a stomachache too.", speaker: "B" },
      { ko: "구토도 하셨어요?", en: "Have you vomited as well?", speaker: "A" },
      { ko: "네, 오늘 아침에 한 번 했어요.", en: "Yes, once this morning.", speaker: "B" },
      { ko: "이 약을 하루 세 번 식후에 복용하세요.", en: "Take this medicine three times a day after meals.", speaker: "A" },
      { ko: "부작용이 생기면 바로 다시 오세요.", en: "If you have side effects, come back right away.", speaker: "A" },
    ],
  },
  {
    id: "clip-apartment",
    kind: "clip",
    track: "opi",
    title: "집 구하기",
    titleEn: "Apartment hunting",
    topic: "Life",
    level: "A2",
    emoji: "🏢",
    sentences: [
      { ko: "이 집은 관리비가 한 달에 얼마예요?", en: "How much is the monthly maintenance fee for this place?", speaker: "B" },
      { ko: "15만 원 정도입니다.", en: "About 150,000 won.", speaker: "A" },
      { ko: "주차장도 있나요?", en: "Is there parking too?", speaker: "B" },
      { ko: "네, 지하 주차장을 무료로 이용하실 수 있어요.", en: "Yes, you can use the underground parking for free.", speaker: "A" },
      { ko: "방이 넉넉해서 마음에 들어요.", en: "The rooms are roomy — I like it.", speaker: "B" },
    ],
  },
  {
    id: "clip-volunteering",
    kind: "clip",
    track: "opi",
    title: "봉사 활동 경험",
    titleEn: "OPI narration: a volunteering experience",
    topic: "Society",
    level: "B1",
    emoji: "🫶",
    sentences: [
      { ko: "지난 주말에 친구들과 고아원에서 자원봉사를 했습니다.", en: "Last weekend I volunteered at an orphanage with friends." },
      { ko: "아이들과 함께 그림을 그리고 점심을 만들었습니다.", en: "We drew pictures and made lunch with the children." },
      { ko: "처음에는 어색했지만 금방 친해졌습니다.", en: "It was awkward at first, but we quickly became close." },
      { ko: "봉사를 하면서 오히려 제가 더 많이 배웠습니다.", en: "Through volunteering, I actually learned more myself." },
      { ko: "앞으로도 꾸준히 봉사 활동을 하고 싶습니다.", en: "I want to keep volunteering regularly from now on." },
    ],
  },
];
