import type { Article, Clip } from "./types";

/**
 * Exam-prep content. DLPT stories mirror the DLPT5's authentic-material
 * topics (security, politics, economy, society, science, North Korea) at
 * roughly ILR 1+ to 2+. OPI clips model the interview's speaking tasks:
 * self-introduction, routine, past narration, opinion, role-play, briefing.
 * All are original texts written for learners.
 */
export const DLPT_ARTICLES: Article[] = [
  {
    id: "dlpt-joint-exercise",
    kind: "news",
    track: "dlpt",
    title: "한미 연합 훈련 시작",
    titleEn: "Korea–US combined exercise begins",
    topic: "Security",
    level: "B1",
    date: "2026-10-05",
    emoji: "🎖️",
    sentences: [
      { ko: "한국과 미국 군대가 오늘부터 열흘 동안 연합 훈련을 실시합니다.", en: "Korean and US forces begin a ten-day combined exercise today." },
      { ko: "이번 훈련에는 육군, 해군, 공군 병력 약 만 명이 참가합니다.", en: "About ten thousand army, navy and air force personnel are taking part." },
      { ko: "국방부는 이번 훈련이 방어적인 성격의 정례 훈련이라고 밝혔습니다.", en: "The Ministry of National Defense said it is a routine exercise of a defensive nature." },
      { ko: "훈련 기간 동안 일부 지역에서는 군용 차량의 이동이 늘어날 예정입니다.", en: "Military vehicle movements are expected to increase in some areas during the exercise." },
      { ko: "군 당국은 주민들에게 소음과 교통 불편에 대해 양해를 구했습니다.", en: "Military authorities asked residents for their understanding about noise and traffic inconvenience." },
      { ko: "북한은 이번 훈련에 대해 강하게 반발하고 있습니다.", en: "North Korea is strongly protesting the exercise." },
    ],
  },
  {
    id: "dlpt-missile-launch",
    kind: "news",
    track: "dlpt",
    title: "북한, 동해상으로 탄도미사일 발사",
    titleEn: "North Korea fires a ballistic missile into the East Sea",
    topic: "Security",
    level: "B2",
    date: "2026-10-03",
    emoji: "🚀",
    sentences: [
      { ko: "합동참모본부는 북한이 오늘 오전 동해상으로 탄도미사일 한 발을 발사했다고 밝혔습니다.", en: "The Joint Chiefs of Staff said North Korea fired one ballistic missile into the East Sea this morning." },
      { ko: "미사일은 약 오백 킬로미터를 비행한 뒤 바다에 떨어진 것으로 알려졌습니다.", en: "The missile reportedly flew about 500 kilometers before falling into the sea." },
      { ko: "우리 군은 감시와 경계를 강화하고 미국과 정보를 긴밀히 공유하고 있습니다.", en: "Our military has stepped up surveillance and vigilance and is closely sharing information with the US." },
      { ko: "정부는 국가안전보장회의를 열고 이번 발사를 강하게 규탄했습니다.", en: "The government convened the National Security Council and strongly condemned the launch." },
      { ko: "전문가들은 북한이 무기 개발을 계속하면서 긴장을 높이려는 의도라고 분석했습니다.", en: "Experts analyzed it as an intent to raise tensions while continuing weapons development." },
      { ko: "유엔 안전보장이사회도 이 문제를 논의할 예정입니다.", en: "The UN Security Council is also expected to discuss the issue." },
    ],
  },
  {
    id: "dlpt-summit",
    kind: "news",
    track: "dlpt",
    title: "한일 정상회담 개최",
    titleEn: "Korea–Japan summit held",
    topic: "Politics",
    level: "B1",
    date: "2026-09-26",
    emoji: "🤝",
    sentences: [
      { ko: "한국과 일본 정상이 오늘 서울에서 정상회담을 가졌습니다.", en: "The leaders of Korea and Japan held a summit in Seoul today." },
      { ko: "두 정상은 경제와 안보 분야에서 협력을 강화하기로 합의했습니다.", en: "The two leaders agreed to strengthen cooperation in the economy and security." },
      { ko: "또한 청년 교류를 늘리고 비자 절차를 간소화하기로 했습니다.", en: "They also decided to expand youth exchanges and simplify visa procedures." },
      { ko: "회담 후 두 정상은 공동 기자회견을 열었습니다.", en: "After the talks, the two leaders held a joint press conference." },
      { ko: "대통령은 양국 관계가 새로운 단계로 발전하고 있다고 말했습니다.", en: "The president said relations between the two countries are developing to a new stage." },
      { ko: "그러나 일부 시민 단체는 역사 문제에 대한 논의가 부족했다고 비판했습니다.", en: "However, some civic groups criticized the lack of discussion on historical issues." },
    ],
  },
  {
    id: "dlpt-election",
    kind: "news",
    track: "dlpt",
    title: "국회의원 선거 투표율 크게 올라",
    titleEn: "Turnout jumps in the National Assembly election",
    topic: "Politics",
    level: "A2",
    date: "2026-09-18",
    emoji: "🗳️",
    sentences: [
      { ko: "어제 실시된 국회의원 선거의 투표율이 70퍼센트를 넘었습니다.", en: "Turnout in yesterday's National Assembly election exceeded 70 percent." },
      { ko: "이는 지난 선거보다 5퍼센트 높은 수치입니다.", en: "That is five percentage points higher than the last election." },
      { ko: "특히 이십 대와 삼십 대 유권자의 참여가 크게 늘었습니다.", en: "Participation by voters in their twenties and thirties rose sharply." },
      { ko: "전문가들은 사전 투표 제도가 투표율 상승에 도움이 되었다고 평가했습니다.", en: "Experts said the early-voting system helped raise turnout." },
      { ko: "새 국회는 다음 달부터 임기를 시작합니다.", en: "The new National Assembly begins its term next month." },
    ],
  },
  {
    id: "dlpt-interest-rate",
    kind: "news",
    track: "dlpt",
    title: "한국은행, 기준금리 동결",
    titleEn: "Bank of Korea holds its base rate",
    topic: "Economy",
    level: "B1",
    date: "2026-10-01",
    emoji: "🏦",
    sentences: [
      { ko: "한국은행이 기준금리를 현재 수준으로 유지하기로 결정했습니다.", en: "The Bank of Korea decided to keep its base rate at the current level." },
      { ko: "물가 상승률은 낮아졌지만 가계 부채가 여전히 높기 때문입니다.", en: "Inflation has eased, but household debt remains high." },
      { ko: "한국은행 총재는 경제 상황을 지켜보며 신중하게 판단하겠다고 밝혔습니다.", en: "The governor said he would watch the economy and judge carefully." },
      { ko: "수출은 반도체를 중심으로 회복세를 보이고 있습니다.", en: "Exports are recovering, led by semiconductors." },
      { ko: "하지만 내수 경기는 아직 부진한 상황입니다.", en: "But domestic demand is still sluggish." },
    ],
  },
  {
    id: "dlpt-enlistment",
    kind: "news",
    track: "dlpt",
    title: "저출산으로 입대 인원 감소",
    titleEn: "Low birth rate shrinks the number of new enlistees",
    topic: "Security",
    level: "B2",
    date: "2026-09-10",
    emoji: "🪖",
    sentences: [
      { ko: "저출산의 영향으로 군에 입대하는 청년의 수가 계속 줄어들고 있습니다.", en: "Because of the low birth rate, the number of young people enlisting keeps falling." },
      { ko: "국방부에 따르면 이십 년 뒤에는 병력이 지금보다 크게 부족해질 수 있습니다.", en: "According to the Ministry of National Defense, troops could be far short of today's level in twenty years." },
      { ko: "정부는 첨단 기술을 활용해 부족한 병력을 보완할 계획입니다.", en: "The government plans to use advanced technology to make up for the shortfall." },
      { ko: "예를 들어 무인 정찰기와 로봇을 경계 임무에 투입하는 방안이 검토되고 있습니다.", en: "For example, deploying reconnaissance drones and robots on guard duty is under review." },
      { ko: "일부에서는 여성의 군 복무를 확대해야 한다는 의견도 나오고 있습니다.", en: "Some are also calling for expanding military service for women." },
    ],
  },
  {
    id: "dlpt-typhoon-relief",
    kind: "news",
    track: "dlpt",
    title: "태풍 피해 복구에 군 장병 투입",
    titleEn: "Troops deployed for typhoon recovery",
    topic: "Society",
    level: "A2",
    date: "2026-08-30",
    emoji: "🌀",
    sentences: [
      { ko: "강한 태풍이 남부 지방을 지나가면서 큰 피해가 발생했습니다.", en: "A strong typhoon passed through the southern region, causing heavy damage." },
      { ko: "많은 집과 도로가 물에 잠겼고 수천 명이 대피했습니다.", en: "Many homes and roads were flooded and thousands evacuated." },
      { ko: "정부는 피해 지역에 군 장병 이천 명을 투입했습니다.", en: "The government deployed two thousand soldiers to the affected areas." },
      { ko: "장병들은 무너진 시설을 정리하고 주민들에게 식수를 나눠 주었습니다.", en: "The soldiers cleared collapsed facilities and handed out drinking water to residents." },
      { ko: "기상청은 이번 주말에 또 다른 태풍이 올 수 있다며 주의를 당부했습니다.", en: "The weather agency urged caution, saying another typhoon could come this weekend." },
    ],
  },
  {
    id: "dlpt-cyber",
    kind: "news",
    track: "dlpt",
    title: "공공기관 겨냥한 사이버 공격 급증",
    titleEn: "Cyber attacks on public institutions surge",
    topic: "Tech",
    level: "B2",
    date: "2026-09-22",
    emoji: "🛡️",
    sentences: [
      { ko: "올해 공공기관을 겨냥한 사이버 공격이 작년보다 크게 늘었습니다.", en: "Cyber attacks targeting public institutions rose sharply this year compared with last year." },
      { ko: "정보 당국은 상당수의 공격이 해외 해커 조직의 소행이라고 밝혔습니다.", en: "Intelligence authorities said many of the attacks were the work of overseas hacker groups." },
      { ko: "해커들은 이메일을 이용해 악성 프로그램을 퍼뜨리는 방식을 주로 사용했습니다.", en: "The hackers mostly used email to spread malicious programs." },
      { ko: "정부는 보안 인력을 늘리고 대응 체계를 강화하기로 했습니다.", en: "The government decided to add security staff and strengthen its response system." },
      { ko: "전문가들은 개인도 비밀번호를 자주 바꾸는 등 기본 보안 수칙을 지켜야 한다고 조언했습니다.", en: "Experts advised individuals to follow basic security rules, such as changing passwords often." },
    ],
  },
  {
    id: "dlpt-nk-food",
    kind: "news",
    track: "dlpt",
    title: "북한 식량 사정 악화",
    titleEn: "North Korea's food situation worsens",
    topic: "World",
    level: "B1",
    date: "2026-09-05",
    emoji: "🌾",
    sentences: [
      { ko: "북한의 식량 사정이 올해 더 나빠진 것으로 보입니다.", en: "North Korea's food situation appears to have worsened this year." },
      { ko: "국제기구는 북한 주민의 상당수가 충분한 식량을 얻지 못하고 있다고 발표했습니다.", en: "An international organization announced that many North Koreans are not getting enough food." },
      { ko: "가뭄과 홍수로 곡물 생산량이 줄었기 때문입니다.", en: "That is because droughts and floods reduced grain production." },
      { ko: "통일부는 인도적 지원을 계속할 의사가 있다고 밝혔습니다.", en: "The Ministry of Unification said it is willing to continue humanitarian aid." },
      { ko: "그러나 북한은 아직 이 제안에 답하지 않았습니다.", en: "However, North Korea has not yet responded to the offer." },
    ],
  },
  {
    id: "dlpt-space-launch",
    kind: "news",
    track: "dlpt",
    title: "한국형 발사체 발사 성공",
    titleEn: "Korea's own space rocket succeeds",
    topic: "Tech",
    level: "B1",
    date: "2026-08-12",
    emoji: "🛰️",
    sentences: [
      { ko: "한국이 독자 기술로 개발한 우주 발사체가 발사에 성공했습니다.", en: "A space launch vehicle Korea developed with its own technology launched successfully." },
      { ko: "발사체는 인공위성을 목표 궤도에 정확히 올려놓았습니다.", en: "The rocket placed a satellite precisely into its target orbit." },
      { ko: "이번 성공으로 한국은 자체 발사 능력을 갖춘 국가가 되었습니다.", en: "With this success, Korea has become a country with its own launch capability." },
      { ko: "정부는 앞으로 달 탐사에도 도전할 계획이라고 밝혔습니다.", en: "The government said it plans to take on lunar exploration in the future." },
    ],
  },
];

export const OPI_CLIPS: Clip[] = [
  {
    id: "opi-introduction",
    kind: "clip",
    track: "opi",
    title: "인터뷰 자기소개",
    titleEn: "OPI warm-up: introduce yourself",
    topic: "Life",
    level: "A2",
    emoji: "🎙️",
    sentences: [
      { ko: "자기소개를 해 주세요.", en: "Please introduce yourself.", speaker: "A" },
      { ko: "저는 미국에서 온 마이클입니다.", en: "I'm Michael, from the US.", speaker: "B" },
      { ko: "지금은 군에서 통역 일을 하고 있습니다.", en: "I currently work as an interpreter in the military.", speaker: "B" },
      { ko: "한국어를 공부한 지 2년 정도 되었습니다.", en: "I've been studying Korean for about two years.", speaker: "B" },
      { ko: "한국어를 왜 배우게 되었어요?", en: "Why did you start learning Korean?", speaker: "A" },
      { ko: "한국 문화에 관심이 많아서 시작하게 되었습니다.", en: "I started because I'm very interested in Korean culture.", speaker: "B" },
    ],
  },
  {
    id: "opi-routine",
    kind: "clip",
    track: "opi",
    title: "하루 일과 말하기",
    titleEn: "OPI level check: describe your day",
    topic: "Life",
    level: "A2",
    emoji: "⏰",
    sentences: [
      { ko: "저는 보통 아침 여섯 시에 일어납니다.", en: "I usually get up at six in the morning." },
      { ko: "일어나서 먼저 운동을 하고 아침을 먹습니다.", en: "After getting up, I exercise first and then eat breakfast." },
      { ko: "여덟 시부터 다섯 시까지 사무실에서 일합니다.", en: "I work in the office from eight to five." },
      { ko: "퇴근한 후에는 한국어 단어를 복습합니다.", en: "After work, I review Korean vocabulary." },
      { ko: "주말에는 친구들과 등산을 가거나 영화를 봅니다.", en: "On weekends I go hiking with friends or watch movies." },
    ],
  },
  {
    id: "opi-past-trip",
    kind: "clip",
    track: "opi",
    title: "지난 여행 이야기",
    titleEn: "OPI level check: narrate a past trip",
    topic: "Life",
    level: "B1",
    emoji: "⛰️",
    sentences: [
      { ko: "지난 여름에 가족과 함께 제주도에 갔습니다.", en: "Last summer I went to Jeju Island with my family." },
      { ko: "첫날에는 비가 와서 호텔에서 쉬었습니다.", en: "On the first day it rained, so we rested at the hotel." },
      { ko: "다음 날에는 날씨가 맑아서 한라산에 올라갔습니다.", en: "The next day was clear, so we climbed Hallasan." },
      { ko: "정상에서 본 경치가 정말 아름다웠습니다.", en: "The view from the summit was truly beautiful." },
      { ko: "다음에는 다른 계절에 꼭 다시 가 보고 싶습니다.", en: "Next time I'd really like to go again in another season." },
    ],
  },
  {
    id: "opi-opinion",
    kind: "clip",
    track: "opi",
    title: "의견 말하기",
    titleEn: "OPI probe: support an opinion",
    topic: "Society",
    level: "B1",
    emoji: "💬",
    sentences: [
      { ko: "대중교통 요금 인상에 대해 어떻게 생각하세요?", en: "What do you think about raising public transit fares?", speaker: "A" },
      { ko: "저는 어느 정도 필요하다고 생각합니다.", en: "I think it's necessary to some extent.", speaker: "B" },
      { ko: "운영 비용이 계속 오르고 있기 때문입니다.", en: "Because operating costs keep rising.", speaker: "B" },
      { ko: "하지만 학생과 노인에게는 할인 혜택을 늘려야 합니다.", en: "But discounts for students and seniors should be expanded.", speaker: "B" },
      { ko: "그래야 모두가 부담 없이 이용할 수 있을 것입니다.", en: "That way everyone can use it without a burden.", speaker: "B" },
    ],
  },
  {
    id: "opi-roleplay",
    kind: "clip",
    track: "opi",
    title: "롤플레이: 호텔 문제 해결",
    titleEn: "OPI role-play: fix a hotel problem",
    topic: "Life",
    level: "A2",
    emoji: "🛎️",
    sentences: [
      { ko: "실례합니다, 방 에어컨이 작동하지 않아요.", en: "Excuse me, the air conditioner in my room isn't working.", speaker: "B" },
      { ko: "불편을 드려서 죄송합니다.", en: "We're sorry for the inconvenience.", speaker: "A" },
      { ko: "바로 직원을 보내 드리겠습니다.", en: "We'll send a staff member right away.", speaker: "A" },
      { ko: "오늘 밤까지 꼭 고쳐 주세요.", en: "Please be sure to fix it by tonight.", speaker: "B" },
      { ko: "안 되면 다른 방으로 바꿔 드릴게요.", en: "If not, we'll move you to another room.", speaker: "A" },
    ],
  },
  {
    id: "opi-briefing",
    kind: "clip",
    track: "opi",
    title: "부대 일정 보고",
    titleEn: "Unit briefing: today's schedule",
    topic: "Security",
    level: "B1",
    emoji: "📋",
    sentences: [
      { ko: "지금부터 오늘의 일정을 보고하겠습니다.", en: "I will now brief today's schedule." },
      { ko: "오전에는 사격 훈련이 있습니다.", en: "There is marksmanship training in the morning." },
      { ko: "오후 두 시에는 장비 점검을 실시합니다.", en: "At 2 p.m. we will conduct an equipment inspection." },
      { ko: "모든 인원은 열두 시까지 식사를 마치기 바랍니다.", en: "All personnel, please finish your meal by twelve." },
      { ko: "이상입니다.", en: "That is all." },
    ],
  },
];
