import type { Article, Clip } from "./types";

/**
 * Third batch of DLPT-style stories and clips, built around the learner's
 * Quizlet DLPT 301–800 cards (see dlptBank.ts). Original texts for learners.
 */
export const DLPT_ARTICLES_3: Article[] = [
  {
    id: "dlpt-ferry-sinking",
    kind: "news",
    track: "dlpt",
    title: "여객선 침몰, 승객 구조 작업 계속",
    titleEn: "Ferry sinks; rescue of passengers continues",
    topic: "World",
    level: "B2",
    date: "2026-10-03",
    emoji: "🚢",
    sentences: [
      { ko: "어제 오후 남해에서 승객 이백 명을 태운 여객선이 침몰했습니다.", en: "Yesterday afternoon a ferry carrying 200 passengers sank off the south coast." },
      { ko: "해경은 헬기와 함정을 출동시켜 밤새 수색 작업을 벌였습니다.", en: "The coast guard dispatched helicopters and vessels and searched through the night." },
      { ko: "지금까지 생존자 백팔십 명이 구조되었지만 열 명은 생사가 확인되지 않고 있습니다.", en: "So far 180 survivors have been rescued, but ten people remain unaccounted for." },
      { ko: "구조된 승객 가운데 세 명은 중태이고 나머지는 생명에 지장이 없는 것으로 알려졌습니다.", en: "Of the rescued passengers, three are in serious condition and the rest are said to be out of danger." },
      { ko: "탑승자 명단과 실제 승객 수가 일치하지 않아 혼란이 커지고 있습니다.", en: "Confusion is growing because the passenger list doesn't match the actual number aboard." },
      { ko: "정부는 사고 원인을 철저히 수사하겠다고 밝혔습니다.", en: "The government said it will thoroughly investigate the cause of the accident." },
    ],
  },
  {
    id: "dlpt-kidnapping",
    kind: "news",
    track: "dlpt",
    title: "초등학생 유괴범 사흘 만에 검거",
    titleEn: "Child kidnapper caught after three days",
    topic: "Security",
    level: "B1",
    date: "2026-09-30",
    emoji: "🧒",
    sentences: [
      { ko: "학교 앞에서 초등학생을 유인해 납치한 유괴범이 사흘 만에 붙잡혔습니다.", en: "A kidnapper who lured an elementary school student away in front of a school was caught after three days." },
      { ko: "범인은 아이에게 장난감을 사 주겠다고 속여 차에 태운 것으로 드러났습니다.", en: "It emerged that the culprit tricked the child into the car by promising to buy a toy." },
      { ko: "경찰은 폐쇄 회로 화면에 찍힌 인상 착의를 공개하고 추격에 나섰습니다.", en: "Police released the suspect's description captured on CCTV and gave chase." },
      { ko: "아이는 무사히 가족의 품으로 돌아갔습니다.", en: "The child returned safely to the family's arms." },
      { ko: "용의자는 경찰 조사에서 범행을 자백했습니다.", en: "The suspect confessed to the crime during police questioning." },
    ],
  },
  {
    id: "dlpt-food-poisoning",
    kind: "news",
    track: "dlpt",
    title: "고등학교 집단 식중독",
    titleEn: "Mass food poisoning at a high school",
    topic: "Society",
    level: "B1",
    date: "2026-09-26",
    emoji: "🤢",
    sentences: [
      { ko: "한 고등학교에서 학생 백여 명이 설사와 복통 등 식중독 증세를 보였습니다.", en: "About a hundred students at a high school showed food-poisoning symptoms such as diarrhea and stomachache." },
      { ko: "학생들은 학교 급식을 먹은 뒤 잇따라 병원으로 옮겨졌습니다.", en: "The students were taken to hospital one after another after eating the school lunch." },
      { ko: "보건 당국은 유통 기한이 지난 재료를 사용했는지 조사하고 있습니다.", en: "Health authorities are investigating whether ingredients past their expiration date were used." },
      { ko: "다행히 위독한 학생은 없는 것으로 알려졌습니다.", en: "Fortunately, no student is reported to be in critical condition." },
      { ko: "교육청은 모든 학교 급식 시설을 점검하기로 했습니다.", en: "The education office decided to inspect all school cafeteria facilities." },
    ],
  },
  {
    id: "dlpt-family-reunion",
    kind: "news",
    track: "dlpt",
    title: "이산가족 상봉 행사 열려",
    titleEn: "Reunion of separated families held",
    topic: "Politics",
    level: "B1",
    date: "2026-09-22",
    emoji: "🫂",
    sentences: [
      { ko: "남북 이산가족 상봉 행사가 삼 년 만에 금강산에서 열렸습니다.", en: "An inter-Korean reunion of separated families was held at Mount Kumgang for the first time in three years." },
      { ko: "구십 대 노인은 칠십 년 동안 연락이 끊겼던 동생을 만나 눈물을 흘렸습니다.", en: "A man in his nineties wept as he met the younger sibling he had lost touch with for seventy years." },
      { ko: "많은 가족이 그동안 서로의 생사도 모른 채 살아왔습니다.", en: "Many families had lived without even knowing whether the other was alive." },
      { ko: "고령의 신청자가 많아 상봉을 정례화해야 한다는 의견이 나오고 있습니다.", en: "Since many applicants are elderly, people are calling for the reunions to be held regularly." },
      { ko: "정부는 북한에 화상 상봉도 제안했습니다.", en: "The government also proposed video reunions to North Korea." },
    ],
  },
  {
    id: "dlpt-defector",
    kind: "news",
    track: "dlpt",
    title: "탈북자 정착 지원 확대",
    titleEn: "More resettlement support for North Korean defectors",
    topic: "Politics",
    level: "B2",
    date: "2026-09-18",
    emoji: "🧭",
    sentences: [
      { ko: "정부는 탈북자들이 한국 사회에 자리를 잡을 수 있도록 지원을 확대하기로 했습니다.", en: "The government decided to expand support so defectors can settle down in Korean society." },
      { ko: "많은 탈북자가 취업난과 차별 때문에 어려움을 겪고 있습니다.", en: "Many defectors struggle because of the tough job market and discrimination." },
      { ko: "앞으로 직업 훈련과 자격증 취득 비용을 정부가 부담합니다.", en: "From now on, the government will cover vocational training and certification costs." },
      { ko: "또 저소득 탈북 가정의 자녀에게는 장학금을 지급할 계획입니다.", en: "It also plans to give scholarships to children of low-income defector families." },
      { ko: "전문가들은 심리적 상담도 함께 제공해야 한다고 지적했습니다.", en: "Experts pointed out that psychological counseling should be provided as well." },
    ],
  },
  {
    id: "dlpt-landmine",
    kind: "news",
    track: "dlpt",
    title: "비무장지대 지뢰 폭발로 장병 부상",
    titleEn: "Landmine blast in the DMZ injures soldiers",
    topic: "Security",
    level: "B2",
    date: "2026-09-14",
    emoji: "💥",
    sentences: [
      { ko: "비무장지대에서 수색 작전을 하던 장병 두 명이 지뢰 폭발로 다쳤습니다.", en: "Two soldiers conducting a search operation in the DMZ were injured by a landmine explosion." },
      { ko: "한 명은 다리에 중상을 입었고 다른 한 명은 가벼운 부상을 당했습니다.", en: "One suffered serious leg injuries and the other was lightly injured." },
      { ko: "군은 북한군이 몰래 침투해 지뢰를 설치했을 가능성을 조사하고 있습니다.", en: "The military is investigating the possibility that North Korean soldiers infiltrated and planted the mine." },
      { ko: "사고 직후 부대는 조명탄을 쏘고 주변을 통제했습니다.", en: "Right after the incident, the unit fired flares and sealed off the area." },
      { ko: "국방부는 이번 사건이 정전 협정을 위반한 것이라고 비판했습니다.", en: "The Ministry of National Defense criticized the incident as a violation of the armistice agreement." },
    ],
  },
  {
    id: "dlpt-train-derailment",
    kind: "news",
    track: "dlpt",
    title: "폭우로 열차 탈선, 운행 중단",
    titleEn: "Heavy rain derails a train; service suspended",
    topic: "Society",
    level: "B1",
    date: "2026-09-10",
    emoji: "🚧",
    sentences: [
      { ko: "폭우로 선로가 물에 잠기면서 하행선 열차가 탈선했습니다.", en: "A southbound train derailed after heavy rain flooded the tracks." },
      { ko: "이 사고로 승객 스무 명이 다쳤지만 사망자는 없었습니다.", en: "Twenty passengers were injured in the accident, but no one was killed." },
      { ko: "사고 구간의 열차 운행이 중단되면서 다른 열차들도 잇따라 연착되었습니다.", en: "With service on that section suspended, other trains were delayed one after another." },
      { ko: "철도 공사는 버스를 투입해 승객들을 다음 역까지 수송했습니다.", en: "The railway corporation brought in buses to carry passengers to the next station." },
      { ko: "선로 복구 작업은 내일 오전까지 지속될 전망입니다.", en: "Track repair work is expected to continue until tomorrow morning." },
    ],
  },
  {
    id: "dlpt-organ-donation",
    kind: "news",
    track: "dlpt",
    title: "뇌사자 장기 기증으로 다섯 명 새 생명",
    titleEn: "Brain-dead donor's organs give five people new life",
    topic: "Society",
    level: "B1",
    date: "2026-09-06",
    emoji: "❤️",
    sentences: [
      { ko: "교통사고로 의식을 잃은 삼십 대 남성이 장기 기증으로 다섯 명에게 새 생명을 주고 세상을 떠났습니다.", en: "A man in his thirties who lost consciousness in a car accident gave five people new life through organ donation before he passed away." },
      { ko: "그의 심장과 신장은 오랫동안 이식을 기다리던 환자들에게 전달되었습니다.", en: "His heart and kidneys went to patients who had long been waiting for transplants." },
      { ko: "유족은 그가 평소에 남을 돕는 일을 좋아했다고 말했습니다.", en: "His bereaved family said he had always liked helping others." },
      { ko: "하지만 국내 장기 기증 희망자 수는 여전히 부족한 상태입니다.", en: "But the number of registered organ donors in Korea is still insufficient." },
      { ko: "정부는 불법 장기 매매를 막기 위해 단속도 강화하고 있습니다.", en: "The government is also stepping up enforcement to stop illegal organ trading." },
    ],
  },
  {
    id: "dlpt-heat-wave",
    kind: "news",
    track: "dlpt",
    title: "폭염에 일사병 환자 급증",
    titleEn: "Heat wave sends heatstroke cases soaring",
    topic: "World",
    level: "A2",
    date: "2026-08-12",
    emoji: "🥵",
    sentences: [
      { ko: "연일 계속되는 폭염으로 일사병 환자가 급증하고 있습니다.", en: "Heatstroke cases are soaring as the heat wave continues day after day." },
      { ko: "기온이 예년보다 삼 도 이상 높고 습도도 매우 높습니다.", en: "Temperatures are more than three degrees above normal, and the humidity is also very high." },
      { ko: "피서철을 맞아 해수욕장과 계곡에는 피서객이 몰렸습니다.", en: "With the summer vacation season, beaches and valleys are packed with vacationers." },
      { ko: "전문가들은 지구 온난화 때문에 폭염이 더 잦아질 것이라고 전망했습니다.", en: "Experts forecast that heat waves will become more frequent due to global warming." },
      { ko: "노인과 어린이는 한낮에 야외 활동을 피하고 물을 충분히 마셔야 합니다.", en: "Seniors and children should avoid outdoor activity at midday and drink enough water." },
    ],
  },
  {
    id: "dlpt-strike",
    kind: "news",
    track: "dlpt",
    title: "버스 노조 파업 예고",
    titleEn: "Bus union announces a strike",
    topic: "Economy",
    level: "B1",
    date: "2026-08-25",
    emoji: "🚌",
    sentences: [
      { ko: "시내버스 노조가 임금 인상을 요구하며 다음 주 파업을 예고했습니다.", en: "The city bus union announced a strike for next week, demanding higher wages." },
      { ko: "노조는 물가가 올랐지만 운전기사의 소득은 몇 년째 그대로라고 주장합니다.", en: "The union argues that prices have risen while drivers' incomes have stayed flat for years." },
      { ko: "회사 측은 경영 사정이 어려워 노조의 요구를 받아들이기 어렵다는 입장입니다.", en: "The company's position is that business is too tough to accept the union's demands." },
      { ko: "시는 파업에 대비해 지하철을 증편하고 전세 버스를 투입할 계획입니다.", en: "The city plans to add subway runs and deploy chartered buses in preparation for the strike." },
      { ko: "시민들은 출근길 불편을 걱정하고 있습니다.", en: "Citizens are worried about inconvenience on their commute." },
    ],
  },
  {
    id: "dlpt-school-bullying",
    kind: "news",
    track: "dlpt",
    title: "학교 집단 괴롭힘 대책 발표",
    titleEn: "Measures against school bullying announced",
    topic: "Society",
    level: "B1",
    date: "2026-08-18",
    emoji: "🏫",
    sentences: [
      { ko: "교육부가 학교 내 집단 괴롭힘을 막기 위한 대책을 발표했습니다.", en: "The Ministry of Education announced measures to prevent group bullying at schools." },
      { ko: "조사 결과 학생 열 명 가운데 한 명이 왕따를 경험한 것으로 나타났습니다.", en: "The survey found that one in ten students had experienced being ostracized." },
      { ko: "피해 학생 중 상당수는 우울증과 같은 심리적 문제를 겪고 있습니다.", en: "Many of the victimized students suffer from psychological problems such as depression." },
      { ko: "앞으로 모든 학교에 전문 상담 교사를 배치하는 것이 의무화됩니다.", en: "From now on it will be mandatory for every school to have a professional counselor." },
      { ko: "가해 학생의 부모도 교육을 받아야 합니다.", en: "Parents of students who bully will also have to take classes." },
    ],
  },
  {
    id: "dlpt-hostage",
    kind: "news",
    track: "dlpt",
    title: "은행 인질극 두 시간 만에 끝나",
    titleEn: "Bank hostage standoff ends after two hours",
    topic: "Security",
    level: "B2",
    date: "2026-08-04",
    emoji: "🏦",
    sentences: [
      { ko: "흉기를 든 남성이 은행에 침입해 직원 세 명을 인질로 잡고 돈을 요구했습니다.", en: "A man armed with a weapon broke into a bank, took three employees hostage and demanded money." },
      { ko: "경찰 특공대가 출동해 은행 주변을 통제하고 범인을 설득했습니다.", en: "A police SWAT team was dispatched, cordoned off the area around the bank and negotiated with the man." },
      { ko: "인질극은 두 시간 만에 범인이 스스로 투항하면서 끝났습니다.", en: "The hostage situation ended after two hours when the man surrendered voluntarily." },
      { ko: "인질들은 다치지 않았지만 심리적 충격을 받아 치료를 받고 있습니다.", en: "The hostages were not hurt but are receiving treatment for psychological shock." },
      { ko: "조사 결과 범인은 빚 때문에 범행을 저질렀으며 전과자로 밝혀졌습니다.", en: "The investigation found the man committed the crime because of debt and had a criminal record." },
    ],
  },
  {
    id: "dlpt-court-ruling",
    kind: "news",
    track: "dlpt",
    title: "음주 운전 사망 사고에 징역형 선고",
    titleEn: "Prison sentence for fatal drunk-driving crash",
    topic: "Society",
    level: "B2",
    date: "2026-07-27",
    emoji: "⚖️",
    sentences: [
      { ko: "법원이 음주 운전으로 정면 충돌 사고를 내 두 명을 숨지게 한 운전자에게 징역형을 선고했습니다.", en: "A court sentenced to prison a driver who caused a head-on collision while drunk, killing two people." },
      { ko: "판사는 판결에서 음주 운전은 다른 사람의 생명을 위협하는 범죄라고 지적했습니다.", en: "In the ruling, the judge pointed out that drunk driving is a crime that threatens other people's lives." },
      { ko: "피고인은 운전 면허 취소에 이어 유족에게 손해 배상도 해야 합니다.", en: "Besides having his license revoked, the defendant must also pay damages to the bereaved families." },
      { ko: "유족은 형량이 너무 가볍다며 항소하겠다고 밝혔습니다.", en: "The families said the sentence is too light and they will appeal." },
      { ko: "경찰은 연말까지 음주 운전 특별 단속을 실시합니다.", en: "Police will run a special drunk-driving crackdown until the end of the year." },
    ],
  },
  {
    id: "dlpt-early-study",
    kind: "news",
    track: "dlpt",
    title: "조기 유학 줄고 입시 경쟁 여전",
    titleEn: "Early study abroad falls; entrance-exam competition persists",
    topic: "Society",
    level: "B1",
    date: "2026-07-21",
    emoji: "🎓",
    sentences: [
      { ko: "경기가 나빠지면서 초등학생 조기 유학이 크게 줄었습니다.", en: "As the economy worsened, early study abroad among elementary students dropped sharply." },
      { ko: "하지만 명문 대학의 입시 경쟁률은 여전히 높습니다.", en: "But entrance-exam competition at top universities remains high." },
      { ko: "학부모들은 자녀의 성적을 올리기 위해 사교육에 많은 돈을 씁니다.", en: "Parents spend a lot on private education to raise their children's grades." },
      { ko: "졸업 후에도 취업난 때문에 대학원에 진학하거나 자격증을 따는 학생이 많습니다.", en: "Even after graduating, many students go to graduate school or earn certifications because of the tight job market." },
      { ko: "전문가들은 학력보다 능력을 중시하는 채용 문화가 필요하다고 말합니다.", en: "Experts say a hiring culture that values ability over education level is needed." },
    ],
  },
];

export const DLPT_CLIPS_3: Clip[] = [
  {
    id: "clip-pickpocket",
    kind: "clip",
    track: "opi",
    title: "파출소에서 소매치기 신고",
    titleEn: "Reporting a pickpocket at the police box",
    topic: "Life",
    level: "B1",
    emoji: "👮",
    sentences: [
      { ko: "시장에서 소매치기를 당했어요.", en: "I got pickpocketed at the market.", speaker: "B" },
      { ko: "범인의 인상 착의를 기억하세요?", en: "Do you remember what the culprit looked like?", speaker: "A" },
      { ko: "키가 크고 검은 모자를 쓴 남자였어요.", en: "It was a tall man wearing a black cap.", speaker: "B" },
      { ko: "가방 안에 무엇이 있었는지 자세히 말씀해 주세요.", en: "Please tell me in detail what was in the bag.", speaker: "A" },
      { ko: "지갑하고 여권이 있었어요.", en: "My wallet and passport.", speaker: "B" },
      { ko: "여권은 대사관에서 다시 발급받으셔야 해요.", en: "You'll need to get your passport reissued at the embassy.", speaker: "A" },
    ],
  },
  {
    id: "clip-delayed-flight",
    kind: "clip",
    track: "opi",
    title: "비행기가 연착됐어요",
    titleEn: "Role-play: a delayed flight",
    topic: "Life",
    level: "A2",
    emoji: "✈️",
    sentences: [
      { ko: "제 비행기가 왜 아직 이륙하지 않았어요?", en: "Why hasn't my flight taken off yet?", speaker: "B" },
      { ko: "기상 악화로 출발이 두 시간 지연되었습니다.", en: "Departure has been delayed two hours due to bad weather.", speaker: "A" },
      { ko: "중요한 회의에 참석해야 하는데 다른 항공편은 없나요?", en: "I have to attend an important meeting — are there no other flights?", speaker: "B" },
      { ko: "오후 비행기로 바꿔 드릴 수 있습니다.", en: "We can change you to an afternoon flight.", speaker: "A" },
      { ko: "그럼 그걸로 해 주세요. 감사합니다.", en: "Then please do that. Thank you.", speaker: "B" },
    ],
  },
  {
    id: "clip-job-interview",
    kind: "clip",
    track: "opi",
    title: "면접에서 장점과 단점",
    titleEn: "Job interview: strengths and weaknesses",
    topic: "Life",
    level: "B1",
    emoji: "💼",
    sentences: [
      { ko: "자신의 장점과 단점을 말해 보세요.", en: "Tell us your strengths and weaknesses.", speaker: "A" },
      { ko: "제 장점은 책임감이 강하고 인내심이 있다는 것입니다.", en: "My strengths are a strong sense of responsibility and patience.", speaker: "B" },
      { ko: "단점은 일을 너무 꼼꼼하게 해서 시간이 오래 걸린다는 것입니다.", en: "My weakness is that I'm so meticulous that work takes me a long time.", speaker: "B" },
      { ko: "그 단점을 고치기 위해 어떤 노력을 하고 있어요?", en: "What are you doing to fix that weakness?", speaker: "A" },
      { ko: "일의 우선순위를 정하고 마감 시간을 지키려고 노력합니다.", en: "I set priorities and try to keep to deadlines.", speaker: "B" },
    ],
  },
  {
    id: "clip-opinion-disposables",
    kind: "clip",
    track: "opi",
    title: "의견 말하기: 일회용품 줄이기",
    titleEn: "OPI opinion: cutting disposable products",
    topic: "Society",
    level: "B2",
    emoji: "♻️",
    sentences: [
      { ko: "저는 일회용품 사용을 법으로 제한해야 한다고 생각합니다.", en: "I think the use of disposable products should be limited by law." },
      { ko: "왜냐하면 폐기물이 늘어나 환경 오염이 심각하기 때문입니다.", en: "Because waste is increasing and environmental pollution is serious." },
      { ko: "예를 들어 카페에서 쓰는 일회용 컵만 해도 하루에 수백만 개입니다.", en: "For example, disposable cups used at cafés alone number in the millions every day." },
      { ko: "물론 소비자는 불편하고 가게는 비용이 늘어난다는 단점도 있습니다.", en: "Of course there are downsides: it's inconvenient for consumers and raises costs for shops." },
      { ko: "그래도 장기적으로 보면 우리 모두에게 유리한 선택이라고 봅니다.", en: "Even so, in the long run I see it as a choice that benefits us all." },
    ],
  },
];
